// ============================================================================
// Generated by melange-solver
// Circuit: "* Wurlitzer 200A Tremolo Oscillator"
//
// This code incorporates substantial portions of GPL-licensed source material
// from the Melange project, including device model equations, Newton-Raphson
// solver logic, matrix operations, and integration templates. It is not a
// mechanical transformation of user input — it is a derived work of Melange's
// copyrighted code and is therefore subject to the GNU General Public License
// v3.0 or later. See https://www.gnu.org/licenses/gpl-3.0.html
// ============================================================================

#![allow(clippy::excessive_precision)]
#![allow(clippy::needless_range_loop)]
#![allow(clippy::too_many_arguments)]
#![allow(unexpected_cfgs)]
#![allow(dead_code)]
#![allow(unused_assignments)]

// =============================================================================
// CONSTANTS: Compile-time circuit topology (Nodal solver)
// =============================================================================

/// Number of augmented system nodes (including VS/VCVS/inductor branch variables)
pub const N: usize = 7;

/// Number of original circuit nodes (excluding ground)
pub const N_NODES: usize = 6;

/// Boundary between VS/VCVS rows and inductor branch variables
pub const N_AUG: usize = 7;

/// Total nonlinear dimension (sum of device dimensions)
pub const M: usize = 2;

/// Maximum NR iterations per sample
pub const MAX_ITER: usize = 70;

/// Chord method: re-factor Jacobian every N iterations (full LU path only).
/// Iter 0 always factors. Between refactors, O(N²) back-solve reuses stored LU.
/// Must be odd — even values can cause refactoring/convergence resonance.
pub const CHORD_REFACTOR: usize = 5;

/// NR convergence tolerance (VNTOL)
pub const TOL: f64 = 1.00000000000000006e-9;

/// Default sample rate (Hz) used at code generation time.
pub const SAMPLE_RATE: f64 = 48000.0;

/// Oversampling factor (1 = none, 2 = 2x, 4 = 4x)
pub const OVERSAMPLING_FACTOR: usize = 1;

/// Input node index
pub const INPUT_NODE: usize = 0;

/// Number of output channels
pub const NUM_OUTPUTS: usize = 1;

/// Output node indices (one per output channel)
pub const OUTPUT_NODES: [usize; NUM_OUTPUTS] = [0];

/// Output scale factors (applied after DC blocking)
pub const OUTPUT_SCALES: [f64; NUM_OUTPUTS] = [1.00000000000000000e0];

/// Input resistance (Thevenin equivalent)
pub const INPUT_RESISTANCE: f64 = 1.00000000000000000e7;

/// Recommended silent-warmup sample count (5τ_max at internal rate, ≥1).
/// See Oomox plugin roadmap P5.
pub const WARMUP_SAMPLES_RECOMMENDED: usize = 9792;

/// G matrix: conductance matrix (sample-rate independent, Gm stripped for IIR op-amps)
const G: [[f64; N]; N] = [
    [
        2.14336546682102638e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        3.70370380370370393e-5,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.94117747058823528e-6,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        2.94117747058823528e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.12765958446808505e-4,
        1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// C matrix: capacitance matrix (sample-rate independent)
const C: [[f64; N]; N] = [
    [
        1.20000999999999990e-7,
        -1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.19999999999999989e-7,
        2.39999999999999979e-7,
        -1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -1.19999999999999989e-7,
        1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A matrix: A = G + (2/T)*C (trapezoidal, at SAMPLE_RATE)
const A_DEFAULT: [[f64; N]; N] = [
    [
        5.97438454668210162e-3,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        -5.75999999999999950e-3,
        1.15570370380370362e-2,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -5.75999999999999950e-3,
        5.76294117747058743e-3,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        5.76294117747058743e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.12765958446808505e-4,
        1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A_neg matrix: A_neg = (2/T)*C - G (trapezoidal history, at SAMPLE_RATE)
const A_NEG_DEFAULT: [[f64; N]; N] = [
    [
        5.76004799999999938e-3,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -5.75999999999999950e-3,
        1.15199999999999990e-2,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -5.75999999999999950e-3,
        5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A_be matrix: A_be = G + (1/T)*C (backward Euler, at SAMPLE_RATE)
const A_BE_DEFAULT: [[f64; N]; N] = [
    [
        5.97438454668210162e-3,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        -5.75999999999999950e-3,
        1.15570370380370362e-2,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -5.75999999999999950e-3,
        5.76294117747058743e-3,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        5.76294117747058743e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.12765958446808505e-4,
        1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A_neg_be matrix: (1/T)*C (backward Euler history, at SAMPLE_RATE)
const A_NEG_BE_DEFAULT: [[f64; N]; N] = [
    [
        5.76004799999999938e-3,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -5.75999999999999950e-3,
        1.15199999999999990e-2,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -5.75999999999999950e-3,
        5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// N_v matrix: extracts controlling voltages from node voltages (M x N)
pub const N_V: [[f64; N]; M] = [
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
        -1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// N_i matrix: maps nonlinear currents to node injections (N x M)
pub const N_I: [[f64; M]; N] = [
    [-1.00000000000000000e0, -1.00000000000000000e0],
    [0.00000000000000000e0, 0.00000000000000000e0],
    [-5.00000000000000010e-3, 0.00000000000000000e0],
    [0.00000000000000000e0, 0.00000000000000000e0],
    [1.00499999999999989e0, -5.00000000000000010e-3],
    [0.00000000000000000e0, 0.00000000000000000e0],
    [0.00000000000000000e0, 0.00000000000000000e0],
];

/// S matrix: A^{-1} (precomputed inverse, trapezoidal, at SAMPLE_RATE)
const S_DEFAULT: [[f64; N]; N] = [
    [
        3.93570275366110354e3,
        3.90857617515149968e3,
        3.90658190297344890e3,
        2.00119543106913866e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.37383564608745412e-1,
    ],
    [
        3.90857617515149923e3,
        4.05405106129103888e3,
        4.05198255218077566e3,
        2.03137662701616328e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.31611952159893475e-1,
    ],
    [
        3.90658190297344800e3,
        4.05198255218077520e3,
        4.22343761665034799e3,
        2.07461965862331743e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.31187638930520833e-1,
    ],
    [
        2.00119543106913866e0,
        2.03137662701616328e0,
        2.07461965862331743e0,
        1.73523546926889310e2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        4.25786261929603921e-4,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        9.99999990000000071e3,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
    ],
    [
        8.37383564608745412e-1,
        8.31611952159893364e-1,
        8.31187638930520833e-1,
        4.25786261929603921e-4,
        0.00000000000000000e0,
        1.00000000000000000e0,
        -3.45992425726073782e-5,
    ],
];

/// K matrix: N_v * S * N_i (nonlinear kernel, trapezoidal, at SAMPLE_RATE)
const K_DEFAULT: [[f64; M]; M] = [
    [-1.39776989905567007e4, -3.85658190347344816e3],
    [1.00499998995000005e4, -4.99999995000000013e1],
];

/// S_NI matrix: S * N_i (precomputed for final voltage recovery, N x M)
const S_NI_DEFAULT: [[f64; M]; N] = [
    [-3.95523566317597079e3, -3.93570275366110354e3],
    [-3.92883608791240295e3, -3.90857617515149923e3],
    [-3.92769909105669967e3, -3.90658190297344800e3],
    [-2.01156852936225539e0, -2.00119543106913866e0],
    [1.00499998995000005e4, -4.99999995000000013e1],
    [0.00000000000000000e0, 0.00000000000000000e0],
    [-8.41539502803398065e-1, -8.37383564608745412e-1],
];

/// S_be matrix: A_be^{-1} (backward Euler, at SAMPLE_RATE)
const S_BE_DEFAULT: [[f64; N]; N] = [
    [
        3.93570275366110354e3,
        3.90857617515149968e3,
        3.90658190297344890e3,
        2.00119543106913866e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.37383564608745412e-1,
    ],
    [
        3.90857617515149923e3,
        4.05405106129103888e3,
        4.05198255218077566e3,
        2.03137662701616328e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.31611952159893475e-1,
    ],
    [
        3.90658190297344800e3,
        4.05198255218077520e3,
        4.22343761665034799e3,
        2.07461965862331743e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.31187638930520833e-1,
    ],
    [
        2.00119543106913866e0,
        2.03137662701616328e0,
        2.07461965862331743e0,
        1.73523546926889310e2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        4.25786261929603921e-4,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        9.99999990000000071e3,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
    ],
    [
        8.37383564608745412e-1,
        8.31611952159893364e-1,
        8.31187638930520833e-1,
        4.25786261929603921e-4,
        0.00000000000000000e0,
        1.00000000000000000e0,
        -3.45992425726073782e-5,
    ],
];

/// K_be matrix: N_v * S_be * N_i (backward Euler kernel)
const K_BE_DEFAULT: [[f64; M]; M] = [
    [-1.39776989905567007e4, -3.85658190347344816e3],
    [1.00499998995000005e4, -4.99999995000000013e1],
];

/// S_NI_be matrix: S_be * N_i (backward Euler, for final voltage recovery)
const S_NI_BE_DEFAULT: [[f64; M]; N] = [
    [-3.95523566317597079e3, -3.93570275366110354e3],
    [-3.92883608791240295e3, -3.90857617515149923e3],
    [-3.92769909105669967e3, -3.90658190297344800e3],
    [-2.01156852936225539e0, -2.00119543106913866e0],
    [1.00499998995000005e4, -4.99999995000000013e1],
    [0.00000000000000000e0, 0.00000000000000000e0],
    [-8.41539502803398065e-1, -8.37383564608745412e-1],
];

/// S_sub matrix: (G + 4C/T)^{-1} (trap at 2× rate, for sub-stepping)
const S_SUB_DEFAULT: [[f64; N]; N] = [
    [
        3.93024962869616047e3,
        3.92344190317112498e3,
        3.92294115104035245e3,
        5.01186453641264906e-1,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.36223325254502159e-1,
    ],
    [
        3.92344190317112407e3,
        3.95997356765249788e3,
        3.95946815277843689e3,
        5.03083122023298412e-1,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.34774873015132757e-1,
    ],
    [
        3.92294115104035200e3,
        3.95946815277843689e3,
        4.00236004047923461e3,
        5.05788501721571748e-1,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.34668330008585424e-1,
    ],
    [
        5.01186453641264795e-1,
        5.03083122023298190e-1,
        5.05788501721571637e-1,
        4.33973021561691255e1,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.06635415668354200e-4,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        9.99999990000000071e3,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
    ],
    [
        8.36223325254502492e-1,
        8.34774873015132979e-1,
        8.34668330008585757e-1,
        1.06635415668354240e-4,
        0.00000000000000000e0,
        1.00000000000000000e0,
        -3.48461020096803301e-5,
    ],
];

/// A_neg_sub matrix: 4C/T - G (trap at 2× rate history)
const A_NEG_SUB_DEFAULT: [[f64; N]; N] = [
    [
        2.28258554533178962e-2,
        -2.30399999999999980e-2,
        0.00000000000000000e0,
        1.47058823529411773e-6,
        0.00000000000000000e0,
        2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        -2.30399999999999980e-2,
        4.60429629619629605e-2,
        -2.30399999999999980e-2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -2.30399999999999980e-2,
        2.30370588225294083e-2,
        1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        1.47058823529411773e-6,
        0.00000000000000000e0,
        1.47058823529411773e-6,
        2.30370588225294083e-2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        -1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        -2.12765958446808505e-4,
        -1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// K_sub matrix: N_v * S_sub * N_i (sub-step kernel)
const K_SUB_DEFAULT: [[f64; M]; M] = [
    [-1.39929528507427494e4, -3.87294115154035217e3],
    [1.00499998995000005e4, -4.99999995000000013e1],
];

/// S_NI_sub matrix: S_sub * N_i (sub-step voltage recovery)
const S_NI_SUB_DEFAULT: [[f64; M]; N] = [
    [-3.94986433445136208e3, -3.93024962869616047e3],
    [-3.94323924393501648e3, -3.92344190317112407e3],
    [-3.94295295124274799e3, -3.92294115104035200e3],
    [-5.03715396149872707e-1, -5.01186453641264795e-1],
    [1.00499998995000005e4, -4.99999995000000013e1],
    [0.00000000000000000e0, 0.00000000000000000e0],
    [-8.40396666904545397e-1, -8.36223325254502492e-1],
];

/// RHS constant contribution from DC sources (trapezoidal: node rows x2, VS rows x1)
pub const RHS_CONST: [f64; N] = [
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    1.50000000000000000e1,
];

/// RHS constant contribution from DC sources (backward Euler: all rows x1)
pub const RHS_CONST_BE: [f64; N] = [
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    1.50000000000000000e1,
];

/// Whether the nonlinear DC OP solver converged at codegen time
pub const DC_OP_CONVERGED: bool = true;

// -----------------------------------------------------------------------------
// Named topology constants (Oomox plugin roadmap P2 + P3).
//
// Plugin code references these instead of hard-coding numeric indices that
// shift when a netlist revision adds or reorders components.
// -----------------------------------------------------------------------------
pub const NODE_OUT: usize = 0;
pub const NODE_NODE_HP: usize = 1;
pub const NODE_BASE3: usize = 2;
pub const NODE_NODE_LP: usize = 3;
pub const NODE_EMIT3: usize = 4;
pub const NODE_VCC: usize = 5;

pub const VSOURCE_V1_RHS_ROW: usize = 6;

// =============================================================================
// DEVICE MODELS
// =============================================================================

const DEVICE_0_IS: f64 = 1.40000000000000003e-14;
const DEVICE_0_VT: f64 = 2.58519910000000012e-2;
const DEVICE_0_BETA_F: f64 = 2.00000000000000000e2;
const DEVICE_0_BETA_R: f64 = 3.00000000000000000e0;
const DEVICE_0_NF: f64 = 1.00000000000000000e0;
const DEVICE_0_NR: f64 = 1.00000000000000000e0;
const DEVICE_0_ISE: f64 = 0.00000000000000000e0;
const DEVICE_0_NE: f64 = 1.50000000000000000e0;
const DEVICE_0_ISC: f64 = 0.00000000000000000e0;
const DEVICE_0_NC: f64 = 2.00000000000000000e0;
const DEVICE_0_SIGN: f64 = 1.0;
const DEVICE_0_USE_GP: bool = false;
const DEVICE_0_VAF: f64 = f64::INFINITY;
const DEVICE_0_VAR: f64 = f64::INFINITY;
const DEVICE_0_IKF: f64 = f64::INFINITY;
const DEVICE_0_IKR: f64 = f64::INFINITY;
const DEVICE_0_VCRIT: f64 = 7.21213101001093038e-1;

const DEVICE_1_IS: f64 = 1.40000000000000003e-14;
const DEVICE_1_VT: f64 = 2.58519910000000012e-2;
const DEVICE_1_BETA_F: f64 = 2.00000000000000000e2;
const DEVICE_1_BETA_R: f64 = 3.00000000000000000e0;
const DEVICE_1_NF: f64 = 1.00000000000000000e0;
const DEVICE_1_NR: f64 = 1.00000000000000000e0;
const DEVICE_1_ISE: f64 = 0.00000000000000000e0;
const DEVICE_1_NE: f64 = 1.50000000000000000e0;
const DEVICE_1_ISC: f64 = 0.00000000000000000e0;
const DEVICE_1_NC: f64 = 2.00000000000000000e0;
const DEVICE_1_SIGN: f64 = 1.0;
const DEVICE_1_USE_GP: bool = false;
const DEVICE_1_VAF: f64 = f64::INFINITY;
const DEVICE_1_VAR: f64 = f64::INFINITY;
const DEVICE_1_IKF: f64 = f64::INFINITY;
const DEVICE_1_IKR: f64 = f64::INFINITY;
const DEVICE_1_VCRIT: f64 = 7.21213101001093038e-1;

/// Fast exp() for audio circuit simulation.
/// Input clamped to [-40, 40] (matches melange safe_exp convention).
///
/// Default: polynomial approximation (<0.0004% error, ~6x faster than libm).
/// To use hardware/libm exp, compile with: `--cfg melange_precise_exp`
#[inline(always)]
fn fast_exp(x: f64) -> f64 {
    #[cfg(melange_precise_exp)]
    {
        x.clamp(-40.0, 40.0).exp()
    }
    #[cfg(not(melange_precise_exp))]
    {
        // Range reduction + 5th-order minimax polynomial. <0.0004% max relative error.
        // No lookup tables, no libm dependency, branchless hot path.
        let x = x.clamp(-40.0, 40.0);
        const LN2_INV: f64 = std::f64::consts::LOG2_E;
        const LN2_HI: f64 = 0.6931471803691238;
        const LN2_LO: f64 = 1.9082149292705877e-10;
        const SHIFT: f64 = 6755399441055744.0; // 2^52 + 2^51
        let z = x * LN2_INV + SHIFT;
        let n_i64 = z.to_bits() as i64 - SHIFT.to_bits() as i64;
        let n = n_i64 as f64;
        let f = (x - n * LN2_HI) - n * LN2_LO;
        let p = 1.0
            + f * (1.0
                + f * (0.5
                    + f * (0.16666666666666607
                        + f * (0.04166666666665876 + f * 0.008333333333492337))));
        let pow2n = f64::from_bits(((1023 + n_i64) as u64) << 52);
        p * pow2n
    }
}

/// Fast ln() for audio circuit simulation.
/// Symmetric log series (~0.005% max relative error, ~3x faster than libm).
/// Only valid for positive inputs.
#[inline(always)]
fn fast_ln(x: f64) -> f64 {
    #[cfg(melange_precise_exp)]
    {
        x.ln()
    }
    #[cfg(not(melange_precise_exp))]
    {
        // Extract exponent and mantissa from IEEE 754 double
        let bits = x.to_bits();
        let e = ((bits >> 52) & 0x7FF) as i64 - 1023;
        // Normalize mantissa to [1, 2)
        let m_bits = (bits & 0x000F_FFFF_FFFF_FFFF) | 0x3FF0_0000_0000_0000;
        let m = f64::from_bits(m_bits);
        // Symmetric log series: u = (m-1)/(m+1), ln(m) = 2u(1 + u²/3 + u⁴/5 + u⁶/7)
        // For m in [1,2), u in [0,1/3): converges much faster than Taylor.
        let u = (m - 1.0) / (m + 1.0);
        let u2 = u * u;
        let ln_m =
            2.0 * u * (1.0 + u2 * (0.3333333333333333 + u2 * (0.2 + u2 * 0.14285714285714285)));
        ln_m + (e as f64) * std::f64::consts::LN_2
    }
}

// Canonical source: melange-primitives/src/nr.rs (pnjlim, fetlim)
// Duplicated here because generated code must be self-contained.

/// SPICE PN junction voltage limiting (from SPICE3f5 DEVpnjlim).
///
/// Limits large forward voltage steps on exponential I-V curves using
/// logarithmic compression. Only activates when vnew > vcrit with large step.
#[inline(always)]
fn pnjlim(vnew: f64, vold: f64, vt: f64, vcrit: f64) -> f64 {
    if vnew > vcrit && (vnew - vold).abs() > vt + vt {
        if vold >= 0.0 {
            let arg = 1.0 + (vnew - vold) / vt;
            if arg > 0.0 {
                vold + vt * arg.ln()
            } else {
                vcrit
            }
        } else {
            vt * (vnew / vt).ln()
        }
    } else {
        vnew
    }
}

/// SPICE FET voltage limiting (from SPICE3f5 DEVfetlim).
///
/// Prevents gate-source voltage from jumping across threshold boundary.
/// The allowed step size adapts to the distance from threshold.
#[inline(always)]
fn fetlim(vnew: f64, vold: f64, vto: f64) -> f64 {
    let delv = vnew - vold;
    let vtox = vto + 3.5;
    let vtsthi = (2.0 * (vold - vto)).abs() + 2.0;
    let vtstlo = vtsthi / 2.0 + 2.0;

    if vold >= vto {
        // Device is "on"
        if vold >= vtox {
            if delv <= 0.0 {
                // Going off
                if vnew >= vtox {
                    if -delv > vtstlo {
                        return vold - vtstlo;
                    }
                } else {
                    return vnew.max(vto + 2.0);
                }
            } else {
                // Staying on
                if delv >= vtsthi {
                    return vold + vtsthi;
                }
            }
        } else {
            // Middle region
            if delv <= 0.0 {
                return vnew.max(vto - 0.5);
            } else {
                return vnew.min(vto + 4.0);
            }
        }
    } else {
        // Device is "off"
        if delv <= 0.0 {
            if -delv > vtstlo {
                return vold - vtstlo;
            }
        } else if vnew <= vto + 0.5 {
            if delv > vtstlo {
                return vold + vtstlo;
            }
        } else {
            return vto + 0.5;
        }
    }
    vnew
}

// Canonical source: melange-devices/src/bjt.rs (BjtEbersMoll, BjtGummelPoon)
// Duplicated here because generated code must be self-contained.

/// Safe exponential using fast_exp (clamp to prevent overflow, matches runtime [-40, 40] range)
#[inline(always)]
fn safe_exp(x: f64) -> f64 {
    fast_exp(x)
}

/// Gummel-Poon base charge factor qb.
///
/// Accounts for Early effect (VAF/VAR) and high-level injection (IKF/IKR).
/// When use_gp=false or all GP params are infinite, returns 1.0 (Ebers-Moll).
///
/// Matches ngspice bjtload.c:571 exactly:
///     q2 = cbe / IKF + cbc / IKR
///     where cbe = IS*(exp(Vbe/(NF*VT)) - 1), cbc = IS*(exp(Vbc/(NR*VT)) - 1)
/// q2 inherits NF/NR emission coefficients via cbe/cbc — it does NOT use bare VT.
#[inline(always)]
fn bjt_qb(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
) -> f64 {
    if !use_gp {
        return 1.0;
    }
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;

    // Early effect: q1 = 1 / (1 - Vbe/VAR - Vbc/VAF)
    let q1_denom = 1.0 - vbe_eff / var - vbc_eff / vaf;
    if q1_denom <= 0.0 || q1_denom.abs() < 1e-30 {
        return 1.0;
    }
    let q1 = 1.0 / q1_denom;

    // High-level injection via cbe/cbc with NF*VT / NR*VT and the -1 term
    // (matches ngspice bjtload.c:571).
    let exp_be = safe_exp(vbe_eff / (nf * vt));
    let exp_bc = safe_exp(vbc_eff / (nr * vt));
    let cbe = is * (exp_be - 1.0);
    let cbc = is * (exp_bc - 1.0);
    let q2 = cbe / ikf + cbc / ikr;

    q1 * (1.0 + (1.0 + 4.0 * q2).max(0.0).sqrt()) / 2.0
}

/// BJT collector current Ic(Vbe, Vbc)
/// sign: +1.0 for NPN, -1.0 for PNP (applied to voltages and output current)
/// nf: forward emission coefficient. Transport current uses exp(Vbe/(NF*VT)).
/// nr: reverse emission coefficient. Reverse current uses exp(Vbc/(NR*VT)).
/// When use_gp=true, divides transport current by qb (Gummel-Poon).
#[inline(always)]
fn bjt_ic(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
) -> f64 {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);
    let i_cc = is * (exp_be - exp_bc);
    let qb = bjt_qb(vbe, vbc, is, vt, nf, nr, sign, use_gp, vaf, var, ikf, ikr);
    sign * (i_cc / qb - is / beta_r * (exp_bc - 1.0))
}

/// BJT base current Ib(Vbe, Vbc)
/// sign: +1.0 for NPN, -1.0 for PNP
/// nf: forward emission coefficient for ideal base current.
/// nr: reverse emission coefficient for reverse base current.
/// ise, ne: B-E leakage saturation current and emission coefficient.
/// isc, nc: B-C leakage saturation current and emission coefficient.
///
/// Matches ngspice bjtload.c:618:
///     cb = cbe/betaF + cben + cbc/betaR + cbcn
/// The ideal forward base current is NOT divided by qb — that is the collector
/// (transport) current's exclusive modification. GP base-current modulation is
/// limited to what the EM forward / reverse / leakage terms already express.
/// The use_gp / GP-param arguments are retained in the signature for call-site
/// stability but are unused in this function.
#[inline(always)]
#[allow(clippy::too_many_arguments)]
fn bjt_ib(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
    _use_gp: bool,
    _vaf: f64,
    _var: f64,
    _ikf: f64,
    _ikr: f64,
) -> f64 {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);
    // Ideal forward + reverse base current (ngspice: cbe/betaF + cbc/betaR, unmodified by qb)
    let ib_fwd = is / beta_f * (exp_be - 1.0);
    let ib_rev = is / beta_r * (exp_bc - 1.0);
    let mut ib = ib_fwd + ib_rev;
    // B-E leakage current: ISE * (exp(Vbe/(NE*VT)) - 1)
    if ise > 0.0 {
        let ne_vt = ne * vt;
        let exp_be_leak = safe_exp(vbe_eff / ne_vt);
        ib += ise * (exp_be_leak - 1.0);
    }
    // B-C leakage current: ISC * (exp(Vbc/(NC*VT)) - 1)
    if isc > 0.0 {
        let nc_vt = nc * vt;
        let exp_bc_leak = safe_exp(vbc_eff / nc_vt);
        ib += isc * (exp_bc_leak - 1.0);
    }
    sign * ib
}

/// BJT Jacobian: [dIc/dVbe, dIc/dVbc, dIb/dVbe, dIb/dVbc]
/// sign: +1.0 for NPN, -1.0 for PNP (s*s=1, so Jacobian entries are polarity-invariant)
/// nf: forward emission coefficient. nr: reverse emission coefficient.
/// ise, ne: B-E leakage. isc, nc: B-C leakage.
/// When use_gp=true, uses quotient rule for d(Icc/qb)/dV (Gummel-Poon).
#[inline(always)]
fn bjt_jacobian(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
) -> [f64; 4] {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);

    // Base current Jacobian (EM components — may be adjusted for GP below)
    let dib_fwd_dvbe = (is / (beta_f * nf_vt)) * exp_be;
    let dib_rev_dvbc = (is / (beta_r * nr_vt)) * exp_bc;
    let mut dib_leak_dvbe = 0.0;
    let mut dib_leak_dvbc = 0.0;
    // ISE leakage contribution to dIb/dVbe
    if ise > 0.0 {
        let ne_vt = ne * vt;
        let exp_be_leak = safe_exp(vbe_eff / ne_vt);
        dib_leak_dvbe = (ise / ne_vt) * exp_be_leak;
    }
    // ISC leakage contribution to dIb/dVbc
    if isc > 0.0 {
        let nc_vt = nc * vt;
        let exp_bc_leak = safe_exp(vbc_eff / nc_vt);
        dib_leak_dvbc = (isc / nc_vt) * exp_bc_leak;
    }

    if !use_gp {
        // Ebers-Moll: simple derivatives
        let dic_dvbe = is / nf_vt * exp_be;
        let dic_dvbc = -(is / nr_vt) * exp_bc - (is / (beta_r * nr_vt)) * exp_bc;
        return [
            dic_dvbe,
            dic_dvbc,
            dib_fwd_dvbe + dib_leak_dvbe,
            dib_rev_dvbc + dib_leak_dvbc,
        ];
    }

    // Gummel-Poon: quotient rule for d(Icc/qb)/dV
    // Icc = is*(exp_be - exp_bc) = cbe - cbc (the -1 terms cancel in the difference)
    let icc = is * (exp_be - exp_bc);
    let dicc_dvbe = is / nf_vt * exp_be;
    let dicc_dvbc = -is / nr_vt * exp_bc;

    // q1 and derivatives
    let q1_denom = 1.0 - vbe_eff / var - vbc_eff / vaf;
    let (q1, dq1_dvbe, dq1_dvbc) = if q1_denom <= 0.0 || q1_denom.abs() < 1e-30 {
        (1.0, 0.0, 0.0)
    } else {
        let q1 = 1.0 / q1_denom;
        (q1, q1 * q1 / var, q1 * q1 / vaf)
    };

    // q2 and derivatives match ngspice bjtload.c:571:
    //     q2 = cbe/IKF + cbc/IKR
    //     cbe = IS*(exp(Vbe/(NF*VT)) - 1), cbc = IS*(exp(Vbc/(NR*VT)) - 1)
    // Reuse exp_be/exp_bc computed above with nf_vt/nr_vt; the -1 constants
    // drop out of the derivatives but matter for q2's value.
    let cbe = is * (exp_be - 1.0);
    let cbc = is * (exp_bc - 1.0);
    let q2 = cbe / ikf + cbc / ikr;
    let dq2_dvbe = (is / (nf_vt * ikf)) * exp_be;
    let dq2_dvbc = (is / (nr_vt * ikr)) * exp_bc;

    // Discriminant D = sqrt(1 + 4*q2)
    let disc = (1.0 + 4.0 * q2).max(0.0);
    let d = disc.sqrt();
    let dd_dvbe = if d > 1e-15 { 2.0 * dq2_dvbe / d } else { 0.0 };
    let dd_dvbc = if d > 1e-15 { 2.0 * dq2_dvbc / d } else { 0.0 };

    // qb = q1 * (1 + D) / 2
    let qb = q1 * (1.0 + d) / 2.0;
    let dqb_dvbe = dq1_dvbe * (1.0 + d) / 2.0 + q1 * dd_dvbe / 2.0;
    let dqb_dvbc = dq1_dvbc * (1.0 + d) / 2.0 + q1 * dd_dvbc / 2.0;

    // Quotient rule: d(Icc/qb)/dV = (dIcc/dV * qb - Icc * dqb/dV) / qb^2
    let qb2 = (qb * qb).max(1e-30);
    let quotient_dvbe = (dicc_dvbe * qb - icc * dqb_dvbe) / qb2;
    let quotient_dvbc = (dicc_dvbc * qb - icc * dqb_dvbc) / qb2;

    let d_bc_term_dvbc = is / (beta_r * nr_vt) * exp_bc;

    // GP base current Jacobian = Ebers-Moll Jacobian (no qb modulation per
    // ngspice bjtload.c:627: gpi = gbe/betaF + gben, gmu = gbc/betaR + gbcn).
    [
        quotient_dvbe,
        quotient_dvbc - d_bc_term_dvbc,
        dib_fwd_dvbe + dib_leak_dvbe,
        dib_rev_dvbc + dib_leak_dvbc,
    ]
}

/// Combined BJT evaluation: returns (Ic, Ib, [dIc/dVbe, dIc/dVbc, dIb/dVbe, dIb/dVbc]).
///
/// Computes exp(Vbe/(NF*VT)) and exp(Vbc/(NR*VT)) once and shares them across current
/// and Jacobian calculations. Reduces from 8-10 exp() to 2-4 per evaluation.
#[inline(always)]
fn bjt_evaluate(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
) -> (f64, f64, [f64; 4]) {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;

    // Shared exponentials (computed once)
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);

    // ISE leakage exponential (computed once, only when needed)
    let exp_be_leak = if ise > 0.0 {
        safe_exp(vbe_eff / (ne * vt))
    } else {
        0.0
    };

    // ISC leakage exponential (computed once, only when needed)
    let exp_bc_leak = if isc > 0.0 {
        safe_exp(vbc_eff / (nc * vt))
    } else {
        0.0
    };

    // === Collector current ===
    let i_cc = is * (exp_be - exp_bc);

    // === Base current components ===
    let ib_fwd = is / beta_f * (exp_be - 1.0);
    let ib_rev = is / beta_r * (exp_bc - 1.0);
    let ib_leak_be = if ise > 0.0 {
        ise * (exp_be_leak - 1.0)
    } else {
        0.0
    };
    let ib_leak_bc = if isc > 0.0 {
        isc * (exp_bc_leak - 1.0)
    } else {
        0.0
    };

    // === Base current Jacobian (EM components) ===
    let dib_fwd_dvbe = (is / (beta_f * nf_vt)) * exp_be;
    let dib_rev_dvbc = (is / (beta_r * nr_vt)) * exp_bc;
    let dib_leak_dvbe = if ise > 0.0 {
        (ise / (ne * vt)) * exp_be_leak
    } else {
        0.0
    };
    let dib_leak_dvbc = if isc > 0.0 {
        (isc / (nc * vt)) * exp_bc_leak
    } else {
        0.0
    };

    if !use_gp {
        // Ebers-Moll
        let ic = sign * (i_cc - is / beta_r * (exp_bc - 1.0));
        let ib = sign * (ib_fwd + ib_rev + ib_leak_be + ib_leak_bc);
        let dic_dvbe = is / nf_vt * exp_be;
        let dic_dvbc = -(is / nr_vt) * exp_bc - (is / (beta_r * nr_vt)) * exp_bc;
        return (
            ic,
            ib,
            [
                dic_dvbe,
                dic_dvbc,
                dib_fwd_dvbe + dib_leak_dvbe,
                dib_rev_dvbc + dib_leak_dvbc,
            ],
        );
    }

    // Gummel-Poon — matches ngspice bjtload.c:565-630
    // q1 and derivatives
    let q1_denom = 1.0 - vbe_eff / var - vbc_eff / vaf;
    let (q1, dq1_dvbe, dq1_dvbc) = if q1_denom <= 0.0 || q1_denom.abs() < 1e-30 {
        (1.0, 0.0, 0.0)
    } else {
        let q1 = 1.0 / q1_denom;
        (q1, q1 * q1 / var, q1 * q1 / vaf)
    };

    // q2 = cbe/IKF + cbc/IKR with cbe = is*(exp_be - 1), cbc = is*(exp_bc - 1)
    // where exp_be/exp_bc already use NF*VT / NR*VT (shared with current calc above).
    // Matches ngspice bjtload.c:571.
    let cbe = is * (exp_be - 1.0);
    let cbc = is * (exp_bc - 1.0);
    let q2 = cbe / ikf + cbc / ikr;
    let dq2_dvbe = (is / (nf_vt * ikf)) * exp_be;
    let dq2_dvbc = (is / (nr_vt * ikr)) * exp_bc;

    // Discriminant D = sqrt(1 + 4*q2)
    let disc = (1.0 + 4.0 * q2).max(0.0);
    let d = disc.sqrt();
    let dd_dvbe = if d > 1e-15 { 2.0 * dq2_dvbe / d } else { 0.0 };
    let dd_dvbc = if d > 1e-15 { 2.0 * dq2_dvbc / d } else { 0.0 };

    // qb = q1 * (1 + D) / 2
    let qb = q1 * (1.0 + d) / 2.0;
    let dqb_dvbe = dq1_dvbe * (1.0 + d) / 2.0 + q1 * dd_dvbe / 2.0;
    let dqb_dvbc = dq1_dvbc * (1.0 + d) / 2.0 + q1 * dd_dvbc / 2.0;

    // Ic: transport current modulated by qb (ngspice bjtload.c:617)
    let ic = sign * (i_cc / qb - is / beta_r * (exp_bc - 1.0));
    // Ib: ideal forward + reverse, NOT divided by qb (ngspice bjtload.c:618)
    let ib = sign * (ib_fwd + ib_rev + ib_leak_be + ib_leak_bc);

    // Quotient rule for dIc: d(Icc/qb)/dV = (dIcc/dV * qb - Icc * dqb/dV) / qb^2
    let dicc_dvbe = is / nf_vt * exp_be;
    let dicc_dvbc = -is / nr_vt * exp_bc;
    let qb2 = (qb * qb).max(1e-30);
    let quotient_dvbe = (dicc_dvbe * qb - i_cc * dqb_dvbe) / qb2;
    let quotient_dvbc = (dicc_dvbc * qb - i_cc * dqb_dvbc) / qb2;
    let d_bc_term_dvbc = is / (beta_r * nr_vt) * exp_bc;

    // dIb Jacobian = pure Ebers-Moll (ngspice bjtload.c:627-628: gpi/gmu are
    // not modulated by qb — GP's modulation affects transport current only).
    (
        ic,
        ib,
        [
            quotient_dvbe,
            quotient_dvbc - d_bc_term_dvbc,
            dib_fwd_dvbe + dib_leak_dvbe,
            dib_rev_dvbc + dib_leak_dvbc,
        ],
    )
}

/// BJT with parasitic resistances (RB, RC, RE).
///
/// Given external junction voltages (Vbe_ext, Vbc_ext), solves for internal
/// junction voltages via inner 2D Newton-Raphson, then returns:
///   (Ic, Ib, [dIc/dVbe_ext, dIc/dVbc_ext, dIb/dVbe_ext, dIb/dVbc_ext])
///
/// The inner NR solves: find (Vbe_int, Vbc_int) such that
///   F1 = Vbe_int - Vbe_ext + Ib*RB + (Ic+Ib)*RE = 0
///   F2 = Vbc_int - Vbc_ext + Ib*RB - Ic*RC = 0
/// (note: RE term uses Ie = -(Ic+Ib), so V_E_int = V_E_ext - Ie*RE = V_E_ext + (Ic+Ib)*RE)
///
/// When RB=RC=RE=0, this reduces to direct evaluation (no inner loop).
#[inline(always)]
fn bjt_with_parasitics(
    vbe_ext: f64,
    vbc_ext: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
    rb: f64,
    rc: f64,
    re: f64,
) -> (f64, f64, [f64; 4]) {
    const INNER_MAX_ITER: usize = 15;
    const INNER_TOL: f64 = 1e-10;

    // Initial guess: internal = external
    let mut vbe_int = vbe_ext;
    let mut vbc_int = vbc_ext;

    for _iter in 0..INNER_MAX_ITER {
        let (ic, ib, jac_int) = bjt_evaluate(
            vbe_int, vbc_int, is, vt, nf, nr, beta_f, beta_r, sign, use_gp, vaf, var, ikf, ikr,
            ise, ne, isc, nc,
        );
        let dic_dvbe = jac_int[0];
        let dic_dvbc = jac_int[1];
        let dib_dvbe = jac_int[2];
        let dib_dvbc = jac_int[3];

        // Residuals
        let f1 = vbe_int - vbe_ext + ib * rb + (ic + ib) * re;
        let f2 = vbc_int - vbc_ext + ib * rb - ic * rc;

        if f1.abs() < INNER_TOL && f2.abs() < INNER_TOL {
            break;
        }

        // Jacobian of F w.r.t. (Vbe_int, Vbc_int)
        let j11 = 1.0 + dib_dvbe * rb + (dic_dvbe + dib_dvbe) * re;
        let j12 = dib_dvbc * rb + (dic_dvbc + dib_dvbc) * re;
        let j21 = dib_dvbe * rb - dic_dvbe * rc;
        let j22 = 1.0 + dib_dvbc * rb - dic_dvbc * rc;

        // Solve 2x2 via Cramer's rule
        let det = j11 * j22 - j12 * j21;
        if det.abs() < 1e-30 {
            break;
        }
        let inv_det = 1.0 / det;
        let dvbe = (j22 * f1 - j12 * f2) * inv_det;
        let dvbc = (j11 * f2 - j21 * f1) * inv_det;

        // Step limiting: max ±4*VT per iteration
        let max_step = 4.0 * vt;
        let dvbe = dvbe.clamp(-max_step, max_step);
        let dvbc = dvbc.clamp(-max_step, max_step);

        vbe_int -= dvbe;
        vbc_int -= dvbc;
    }

    // Final evaluation at converged internal voltages
    let (ic, ib, jac_int) = bjt_evaluate(
        vbe_int, vbc_int, is, vt, nf, nr, beta_f, beta_r, sign, use_gp, vaf, var, ikf, ikr, ise,
        ne, isc, nc,
    );

    // External Jacobian: J_ext = J_device * J_F^{-1}
    // J_F = [[j11, j12], [j21, j22]] (recompute at converged point)
    let dic_dvbe = jac_int[0];
    let dic_dvbc = jac_int[1];
    let dib_dvbe = jac_int[2];
    let dib_dvbc = jac_int[3];

    let j11 = 1.0 + dib_dvbe * rb + (dic_dvbe + dib_dvbe) * re;
    let j12 = dib_dvbc * rb + (dic_dvbc + dib_dvbc) * re;
    let j21 = dib_dvbe * rb - dic_dvbe * rc;
    let j22 = 1.0 + dib_dvbc * rb - dic_dvbc * rc;

    let det = j11 * j22 - j12 * j21;
    if det.abs() < 1e-30 {
        // Fallback: return intrinsic Jacobian
        return (ic, ib, jac_int);
    }
    let inv_det = 1.0 / det;

    // J_F^{-1} = [[j22, -j12], [-j21, j11]] / det
    let fi11 = j22 * inv_det;
    let fi12 = -j12 * inv_det;
    let fi21 = -j21 * inv_det;
    let fi22 = j11 * inv_det;

    // J_ext = J_device * J_F^{-1}
    let dic_dvbe_ext = dic_dvbe * fi11 + dic_dvbc * fi21;
    let dic_dvbc_ext = dic_dvbe * fi12 + dic_dvbc * fi22;
    let dib_dvbe_ext = dib_dvbe * fi11 + dib_dvbc * fi21;
    let dib_dvbc_ext = dib_dvbe * fi12 + dib_dvbc * fi22;

    (
        ic,
        ib,
        [dic_dvbe_ext, dic_dvbc_ext, dib_dvbe_ext, dib_dvbc_ext],
    )
}

// =============================================================================
// STATE STRUCTURE (Nodal solver)
// =============================================================================

/// DC operating point: steady-state node voltages
pub const DC_OP: [f64; N] = [
    4.26480459001615220e0,
    0.00000000000000000e0,
    1.24642300964354735e0,
    2.75561286292147534e0,
    6.66518981635892516e-1,
    1.50000000000000000e1,
    -2.28408414478379392e-3,
];

/// DC operating point: nonlinear device currents at bias point
pub const DC_NL_I: [f64; M] = [7.72841164902171042e-5, 2.20372764851210334e-3];

/// Circuit state for one processing channel (nodal solver).
///
/// Contains per-sample state and sample-rate-dependent matrices.
/// Call [`set_sample_rate`](CircuitState::set_sample_rate) before processing
/// if the host sample rate differs from [`SAMPLE_RATE`].
#[derive(Clone, Debug)]
pub struct CircuitState {
    /// Previous node voltages v[n-1]
    pub v_prev: [f64; N],

    /// Previous nonlinear currents i_nl[n-1]
    pub i_nl_prev: [f64; M],

    /// Nonlinear currents from two samples ago i_nl[n-2] (for NR predictor)
    pub i_nl_prev_prev: [f64; M],

    /// DC operating point (for reset/sleep/wake)
    pub dc_operating_point: [f64; N],

    /// Previous input sample for trapezoidal integration
    pub input_prev: f64,

    /// NR convergence diagnostic from the last sample's solve.
    ///
    /// Semantics:
    /// - 0..MAX_ITER-1: 0-indexed iteration at which convergence was detected
    ///   (i.e. `last_nr_iterations + 1` iterations actually ran)
    /// - MAX_ITER: loop exhausted without convergence → NR failed
    ///
    /// The check `last_nr_iterations >= MAX_ITER` is the BE-fallback trigger;
    /// storing `iter` (not `iter + 1`) is intentional so that convergence at
    /// the final permitted iteration (iter == MAX_ITER - 1) does not false-trigger.
    pub last_nr_iterations: u32,

    /// Diagnostic: peak absolute output (pre-clamp)
    pub diag_peak_output: f64,
    /// Diagnostic: number of times output exceeded +/-10V
    pub diag_clamp_count: u64,
    /// Diagnostic: number of times NR hit max iterations
    pub diag_nr_max_iter_count: u64,
    /// Diagnostic: number of backward Euler fallback activations
    pub diag_be_fallback_count: u64,
    /// Diagnostic: number of times NaN triggered state reset
    pub diag_nan_reset_count: u64,
    /// Diagnostic: number of samples that needed adaptive sub-stepping
    pub diag_substep_count: u64,
    /// Diagnostic: number of LU refactorizations performed
    pub diag_refactor_count: u64,
    /// Diagnostic: number of samples hit by the global voltage-damping
    /// safety net. This is a legacy safeguard that scales v_new toward
    /// v_prev when any node moves more than ~2V (or 5% of max DC OP) in
    /// one sample. Per CLAUDE.md, output limiting must never mask solver
    /// bugs — treat a nonzero count here as a signal that the solver needs
    /// investigation, not as an acceptable steady-state.
    pub diag_voltage_damp_count: u64,

    // --- Cross-timestep chord method state (persisted LU factors) ---
    /// LU-factored Jacobian from previous convergence (chord method)
    pub chord_lu: [[f64; N]; N],
    /// Row equilibration scaling from LU factorization
    pub chord_dr: [f64; N],
    /// Column equilibration scaling from LU factorization
    pub chord_dc: [f64; N],
    /// Row permutation from LU factorization
    pub chord_perm: [usize; N],
    /// Device Jacobian consistent with chord_lu (for companion RHS)
    pub chord_j_dev: [f64; M * M],
    /// Whether chord LU factors are valid (false until first convergence)
    pub chord_valid: bool,

    /// A matrix: G + alpha*C (trapezoidal), recomputed by set_sample_rate
    pub a: [[f64; N]; N],
    /// A_neg matrix: alpha*C - G (trapezoidal history), recomputed by set_sample_rate
    pub a_neg: [[f64; N]; N],
    /// A_be matrix: G + (1/T)*C (backward Euler), recomputed by set_sample_rate
    pub a_be: [[f64; N]; N],
    /// A_neg_be matrix: (1/T)*C (backward Euler history), recomputed by set_sample_rate
    pub a_neg_be: [[f64; N]; N],
    /// S matrix: A^{-1} (trapezoidal), recomputed by set_sample_rate
    pub s: [[f64; N]; N],
    /// K matrix: N_v * S * N_i (nonlinear kernel), recomputed by set_sample_rate
    pub k: [[f64; M]; M],
    /// S_NI matrix: S * N_i (voltage recovery), recomputed by set_sample_rate
    pub s_ni: [[f64; M]; N],
    /// S_be matrix: A_be^{-1} (backward Euler), recomputed by set_sample_rate
    pub s_be: [[f64; N]; N],
    /// K_be matrix: N_v * S_be * N_i (BE kernel), recomputed by set_sample_rate
    pub k_be: [[f64; M]; M],
    /// S_NI_be matrix: S_be * N_i (BE voltage recovery), recomputed by set_sample_rate
    pub s_ni_be: [[f64; M]; N],
    /// S_sub matrix: (G+4C/T)^{-1} (trap at 2× rate), recomputed by set_sample_rate
    pub s_sub: [[f64; N]; N],
    /// A_neg_sub matrix: 4C/T-G (trap at 2× rate history), recomputed by set_sample_rate
    pub a_neg_sub: [[f64; N]; N],
    /// K_sub matrix: N_v*S_sub*N_i (sub-step kernel)
    pub k_sub: [[f64; M]; M],
    /// S_NI_sub matrix: S_sub*N_i (sub-step voltage recovery)
    pub s_ni_sub: [[f64; M]; N],

    // --- Runtime-adjustable device parameters ---
    /// Device 0 IS (Bjt) — runtime adjustable
    pub device_0_is: f64,
    /// Device 0 VT (Bjt) — runtime adjustable
    pub device_0_vt: f64,
    /// Device 0 BETA_F (Bjt) — runtime adjustable
    pub device_0_bf: f64,
    /// Device 0 BETA_R (Bjt) — runtime adjustable
    pub device_0_br: f64,
    /// Device 1 IS (Bjt) — runtime adjustable
    pub device_1_is: f64,
    /// Device 1 VT (Bjt) — runtime adjustable
    pub device_1_vt: f64,
    /// Device 1 BETA_F (Bjt) — runtime adjustable
    pub device_1_bf: f64,
    /// Device 1 BETA_R (Bjt) — runtime adjustable
    pub device_1_br: f64,
}

impl Default for CircuitState {
    fn default() -> Self {
        let mut state = Self {
            v_prev: DC_OP,
            i_nl_prev: DC_NL_I,
            i_nl_prev_prev: DC_NL_I,
            dc_operating_point: DC_OP,
            input_prev: 0.0,
            last_nr_iterations: 0,
            diag_peak_output: 0.0,
            diag_clamp_count: 0,
            diag_nr_max_iter_count: 0,
            diag_be_fallback_count: 0,
            diag_nan_reset_count: 0,
            diag_substep_count: 0,
            diag_refactor_count: 0,
            diag_voltage_damp_count: 0,
            chord_lu: [[0.0; N]; N],
            chord_dr: [1.0; N],
            chord_dc: [1.0; N],
            chord_perm: {
                {
                    let mut p = [0usize; N];
                    let mut i = 0;
                    while i < N {
                        p[i] = i;
                        i += 1;
                    }
                    p
                }
            },
            chord_j_dev: [0.0; M * M],
            chord_valid: false,
            a: A_DEFAULT,
            a_neg: A_NEG_DEFAULT,
            a_be: A_BE_DEFAULT,
            a_neg_be: A_NEG_BE_DEFAULT,
            s: S_DEFAULT,
            k: K_DEFAULT,
            s_ni: S_NI_DEFAULT,
            s_be: S_BE_DEFAULT,
            s_sub: S_SUB_DEFAULT,
            a_neg_sub: A_NEG_SUB_DEFAULT,
            k_sub: K_SUB_DEFAULT,
            s_ni_sub: S_NI_SUB_DEFAULT,
            k_be: K_BE_DEFAULT,
            s_ni_be: S_NI_BE_DEFAULT,
            device_0_is: DEVICE_0_IS,
            device_0_vt: DEVICE_0_VT,
            device_0_bf: DEVICE_0_BETA_F,
            device_0_br: DEVICE_0_BETA_R,
            device_1_is: DEVICE_1_IS,
            device_1_vt: DEVICE_1_VT,
            device_1_bf: DEVICE_1_BETA_F,
            device_1_br: DEVICE_1_BETA_R,
        };
        state.warmup();
        state
    }
}

impl CircuitState {
    /// Reset to DC operating point
    pub fn reset(&mut self) {
        self.v_prev = self.dc_operating_point;
        self.i_nl_prev = DC_NL_I;
        self.i_nl_prev_prev = DC_NL_I;
        self.input_prev = 0.0;
        self.last_nr_iterations = 0;
        self.chord_valid = false;
        self.diag_peak_output = 0.0;
        self.diag_clamp_count = 0;
        self.diag_nr_max_iter_count = 0;
        self.diag_be_fallback_count = 0;
        self.diag_nan_reset_count = 0;
        self.diag_voltage_damp_count = 0;
        self.diag_substep_count = 0;
        self.diag_refactor_count = 0;
        self.s = S_DEFAULT;
        self.k = K_DEFAULT;
        self.s_ni = S_NI_DEFAULT;
        self.s_be = S_BE_DEFAULT;
        self.k_be = K_BE_DEFAULT;
        self.s_ni_be = S_NI_BE_DEFAULT;
        self.s_sub = S_SUB_DEFAULT;
        self.a_neg_sub = A_NEG_SUB_DEFAULT;
        self.k_sub = K_SUB_DEFAULT;
        self.s_ni_sub = S_NI_SUB_DEFAULT;
        self.device_0_is = DEVICE_0_IS;
        self.device_0_vt = DEVICE_0_VT;
        self.device_0_bf = DEVICE_0_BETA_F;
        self.device_0_br = DEVICE_0_BETA_R;
        self.device_1_is = DEVICE_1_IS;
        self.device_1_vt = DEVICE_1_VT;
        self.device_1_bf = DEVICE_1_BETA_F;
        self.device_1_br = DEVICE_1_BETA_R;
        self.warmup();
    }

    /// Run silent warmup samples to settle into the correct operating point.
    ///
    /// Call after construction or reset() to ensure the circuit settles into
    /// the physically correct basin of attraction. Without warmup, circuits
    /// with high-gain op-amps may lock into a parasitic equilibrium.
    ///
    /// The default `CircuitState::default()` calls this automatically.
    pub fn warmup(&mut self) {
        for _ in 0..50 {
            process_sample(0.0, self);
        }
    }

    /// Set DC operating point (call after DC analysis)
    pub fn set_dc_operating_point(&mut self, v_dc: [f64; N]) {
        self.dc_operating_point = v_dc;
        self.v_prev = v_dc;
    }

    /// Read the baked DC operating point for this circuit.
    ///
    /// Solution to the nonlinear DC system computed at codegen time (at nominal
    /// pot/switch values) and frozen into `DC_OP`. Prefer this over `v_prev` when
    /// you want the *designed* bias point — `v_prev` carries per-sample dynamics.
    #[inline]
    pub fn dc_op(&self) -> &[f64; N] {
        &self.dc_operating_point
    }

    /// Pretty-print the DC operating point with user-assigned node names.
    ///
    /// Writes one line per named node to `stderr`. Intended for plugin
    /// bring-up diagnostics, not the audio thread (formatting allocates).
    pub fn dc_op_dump(&self) {
        let dc = &self.dc_operating_point;
        eprintln!("  V(OUT) = {:+.4} V", dc[0]);
        eprintln!("  V(NODE_HP) = {:+.4} V", dc[1]);
        eprintln!("  V(BASE3) = {:+.4} V", dc[2]);
        eprintln!("  V(NODE_LP) = {:+.4} V", dc[3]);
        eprintln!("  V(EMIT3) = {:+.4} V", dc[4]);
        eprintln!("  V(VCC) = {:+.4} V", dc[5]);
    }

    /// Recompute all sample-rate-dependent matrices for a new sample rate.
    ///
    /// Call this once during plugin initialization (NOT on the audio thread).
    /// Rebuilds A, A_neg, A_be, A_neg_be from stored G and C matrices.
    pub fn set_sample_rate(&mut self, sample_rate: f64) {
        if !(sample_rate > 0.0 && sample_rate.is_finite()) {
            return;
        }

        // If same as codegen sample rate, reset to defaults
        if (sample_rate - SAMPLE_RATE).abs() < 0.5 {
            self.a = A_DEFAULT;
            self.a_neg = A_NEG_DEFAULT;
            self.a_be = A_BE_DEFAULT;
            self.a_neg_be = A_NEG_BE_DEFAULT;
            self.s = S_DEFAULT;
            self.s_be = S_BE_DEFAULT;
            self.k = K_DEFAULT;
            self.s_ni = S_NI_DEFAULT;
            self.k_be = K_BE_DEFAULT;
            self.s_ni_be = S_NI_BE_DEFAULT;
            return;
        }

        let internal_rate = sample_rate * 1.0;
        self.rebuild_matrices(internal_rate);
    }

    /// Recompute A, A_neg, A_be, A_neg_be, S, K, S_NI (and BE variants) from G and C.
    ///
    /// Called by set_sample_rate, set_pot, and set_switch.
    /// Includes O(N^3) matrix inversion for Schur complement NR.
    pub fn rebuild_matrices(&mut self, internal_rate: f64) {
        let alpha = internal_rate; // backward Euler: alpha = 1/T
        let alpha_be = internal_rate;
        let alpha_sub = 4.0 * internal_rate; // trap at 2× rate

        for i in 0..N {
            for j in 0..N {
                self.a[i][j] = G[i][j] + alpha * C[i][j];
                self.a_neg[i][j] = alpha * C[i][j];
                self.a_be[i][j] = G[i][j] + alpha_be * C[i][j];
                self.a_neg_be[i][j] = alpha_be * C[i][j];
            }
        }
        for i in 0..N {
            for j in 0..N {
                self.a_neg_sub[i][j] = alpha_sub * C[i][j] - G[i][j];
            }
        }
        for i in 6..7 {
            for j in 0..N {
                self.a_neg[i][j] = 0.0;
                self.a_neg_be[i][j] = 0.0;
            }
        }
        for i in 6..7 {
            for j in 0..N {
                self.a_neg_sub[i][j] = 0.0;
            }
        }

        // Recompute S = A^{-1} (trapezoidal)
        if let Some(inv) = invert_n(&self.a) {
            self.s = inv;
            // K = N_v * S * N_i
            for i in 0..M {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        let mut s_ni_aj = 0.0;
                        for b in 0..N {
                            s_ni_aj += self.s[a][b] * N_I[b][j];
                        }
                        sum += N_V[i][a] * s_ni_aj;
                    }
                    self.k[i][j] = sum;
                }
            }
            // S_NI = S * N_i
            for i in 0..N {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        sum += self.s[i][a] * N_I[a][j];
                    }
                    self.s_ni[i][j] = sum;
                }
            }
        }
        // Recompute S_be = A_be^{-1} (backward Euler)
        if let Some(inv) = invert_n(&self.a_be) {
            self.s_be = inv;
            for i in 0..M {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        let mut s_ni_aj = 0.0;
                        for b in 0..N {
                            s_ni_aj += self.s_be[a][b] * N_I[b][j];
                        }
                        sum += N_V[i][a] * s_ni_aj;
                    }
                    self.k_be[i][j] = sum;
                }
            }
            for i in 0..N {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        sum += self.s_be[i][a] * N_I[a][j];
                    }
                    self.s_ni_be[i][j] = sum;
                }
            }
        }
        // Recompute S_sub = (G + alpha_sub*C)^{-1} (trap at 2× rate)
        let mut a_sub = [[0.0f64; N]; N];
        for i in 0..N {
            for j in 0..N {
                a_sub[i][j] = G[i][j] + alpha_sub * C[i][j];
            }
        }
        if let Some(inv) = invert_n(&a_sub) {
            self.s_sub = inv;
            for i in 0..M {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        let mut s_ni_aj = 0.0;
                        for b in 0..N {
                            s_ni_aj += self.s_sub[a][b] * N_I[b][j];
                        }
                        sum += N_V[i][a] * s_ni_aj;
                    }
                    self.k_sub[i][j] = sum;
                }
            }
            for i in 0..N {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        sum += self.s_sub[i][a] * N_I[a][j];
                    }
                    self.s_ni_sub[i][j] = sum;
                }
            }
        }

        // Invalidate chord LU cache (matrices changed)
        self.chord_valid = false;
    }
}

// =============================================================================
// MATRIX INVERSION (for rebuild_matrices)
// =============================================================================

/// Invert an N×N matrix via LU factorization with partial pivoting.
/// Returns None if the matrix is singular (pivot < 1e-30).
///
/// Called three times per `rebuild_matrices` on the nodal path
/// (S = A^-1, S_be = A_be^-1, S_sub = A_sub^-1), so factor-then-
/// solve uses ~half the work of the prior Gauss-Jordan on an
/// augmented [A | I] matrix and halves the stack footprint.
#[inline(never)]
fn invert_n(a: &[[f64; N]; N]) -> Option<[[f64; N]; N]> {
    let mut lu = *a;
    let mut perm = [0usize; N];
    for i in 0..N {
        perm[i] = i;
    }

    for k in 0..N {
        let mut max_row = k;
        let mut max_val = lu[k][k].abs();
        for i in (k + 1)..N {
            let v = lu[i][k].abs();
            if v > max_val {
                max_val = v;
                max_row = i;
            }
        }
        if max_val < 1e-30 {
            return None;
        }
        if max_row != k {
            lu.swap(k, max_row);
            perm.swap(k, max_row);
        }
        let pivot = lu[k][k];
        for i in (k + 1)..N {
            let m = lu[i][k] / pivot;
            lu[i][k] = m;
            for j in (k + 1)..N {
                lu[i][j] -= m * lu[k][j];
            }
        }
    }

    let mut result = [[0.0f64; N]; N];
    for col in 0..N {
        let mut b = [0.0f64; N];
        let mut start = N;
        for i in 0..N {
            if perm[i] == col {
                b[i] = 1.0;
                start = i;
                break;
            }
        }
        for i in (start + 1)..N {
            let mut sum = b[i];
            for j in start..i {
                sum -= lu[i][j] * b[j];
            }
            b[i] = sum;
        }
        for i in (0..N).rev() {
            let mut sum = b[i];
            for j in (i + 1)..N {
                sum -= lu[i][j] * b[j];
            }
            let pivot = lu[i][i];
            if pivot.abs() < 1e-30 {
                return None;
            }
            b[i] = sum / pivot;
        }
        for i in 0..N {
            result[i][col] = b[i];
        }
    }

    Some(result)
}

// =============================================================================
// PROCESS SAMPLE (Schur complement: M-dim NR via precomputed S = A^{-1})
// =============================================================================

/// Process a single audio sample through the circuit.
///
/// Uses Schur complement NR: precomputes S = A^{-1}, iterates in M-space.
/// Cost: O(N^2) linear prediction + O(M^3) per NR iteration.
#[inline]
pub fn process_sample(input: f64, state: &mut CircuitState) -> [f64; NUM_OUTPUTS] {
    let input = if input.is_finite() {
        input.clamp(-100.0, 100.0)
    } else {
        0.0
    };

    for v in state.v_prev.iter_mut() {
        *v = *v + 1e-25 - 1e-25;
    }
    for v in state.i_nl_prev.iter_mut() {
        *v = *v + 1e-25 - 1e-25;
    }

    // Step 1: Build RHS (sparse A_neg * v_prev + sparse N_i * i_nl_prev)
    let mut rhs = RHS_CONST;
    rhs[0] += state.a_neg[0][0] * state.v_prev[0];
    rhs[0] += state.a_neg[0][1] * state.v_prev[1];
    rhs[1] += state.a_neg[1][0] * state.v_prev[0];
    rhs[1] += state.a_neg[1][1] * state.v_prev[1];
    rhs[1] += state.a_neg[1][2] * state.v_prev[2];
    rhs[2] += state.a_neg[2][1] * state.v_prev[1];
    rhs[2] += state.a_neg[2][2] * state.v_prev[2];
    rhs[3] += state.a_neg[3][3] * state.v_prev[3];

    let input_conductance = 1.0 / INPUT_RESISTANCE;
    // Input source (backward Euler: V_in * G_in)
    rhs[INPUT_NODE] += input * input_conductance;
    state.input_prev = input;

    // Step 2: Linear prediction v_pred = S * rhs (O(N^2))
    let mut v_pred = [0.0f64; N];
    for i in 0..N {
        let mut sum = 0.0;
        for j in 0..N {
            sum += state.s[i][j] * rhs[j];
        }
        v_pred[i] = sum;
    }

    // Step 3: Extract device voltages p = N_v * v_pred (sparse)
    let mut p = [0.0f64; M];
    p[0] = N_V[0][2] * v_pred[2] + N_V[0][4] * v_pred[4];
    p[1] = N_V[1][4] * v_pred[4];

    // Step 4: M-dim Newton-Raphson (Schur complement)
    // First-order predictor warm start
    let mut i_nl = [0.0f64; M];
    for i in 0..M {
        i_nl[i] = 2.0 * state.i_nl_prev[i] - state.i_nl_prev_prev[i];
    }
    let mut converged = false;
    state.last_nr_iterations = MAX_ITER as u32;

    for iter in 0..MAX_ITER {
        // 4a. Compute controlling voltages: v_d = p + K * i_nl
        let v_d0 = p[0] + state.k[0][0] * i_nl[0] + state.k[0][1] * i_nl[1];
        let v_d1 = p[1] + state.k[1][0] * i_nl[0] + state.k[1][1] * i_nl[1];

        // 4b. Evaluate device currents and Jacobians
        let vbe_0 = v_d0 * DEVICE_0_SIGN;
        let exp_be_0 = fast_exp(vbe_0 / (DEVICE_0_NF * state.device_0_vt));
        let i_dev0 = state.device_0_is * (exp_be_0 - 1.0) * DEVICE_0_SIGN;
        let jdev_0_0 = state.device_0_is / (DEVICE_0_NF * state.device_0_vt) * exp_be_0;
        let vbe_1 = v_d1 * DEVICE_1_SIGN;
        let exp_be_1 = fast_exp(vbe_1 / (DEVICE_1_NF * state.device_1_vt));
        let i_dev1 = state.device_1_is * (exp_be_1 - 1.0) * DEVICE_1_SIGN;
        let jdev_1_1 = state.device_1_is / (DEVICE_1_NF * state.device_1_vt) * exp_be_1;

        // 4c. Residuals: f(i) = i_nl - i_dev = 0
        let f0 = i_nl[0] - i_dev0;
        let f1 = i_nl[1] - i_dev1;

        // 4d. Jacobian: J[i][j] = delta_ij - jdev * K
        let j0_0 = 1.0 - jdev_0_0 * state.k[0][0];
        let j0_1 = 0.0 - jdev_0_0 * state.k[0][1];
        let j1_0 = 0.0 - jdev_1_1 * state.k[1][0];
        let j1_1 = 1.0 - jdev_1_1 * state.k[1][1];

        // Solve 2x2 (Cramer's rule)
        let det = j0_0 * j1_1 - j0_1 * j1_0;
        if det.abs() < 1e-15 {
            // Singular Jacobian — damped fallback (0.5 * residual, adaptive clamp)
            {
                let clamp = (i_nl[0].abs() * 0.1).max(0.01);
                i_nl[0] -= (f0 * 0.5).clamp(-clamp, clamp);
            }
            {
                let clamp = (i_nl[1].abs() * 0.1).max(0.01);
                i_nl[1] -= (f1 * 0.5).clamp(-clamp, clamp);
            }
            continue;
        }
        let inv_det = 1.0 / det;
        let delta0 = inv_det * (j1_1 * f0 - j0_1 * f1);
        let delta1 = inv_det * (-j1_0 * f0 + j0_0 * f1);

        // Trial voltages: apply full NR step, then limit
        let i_trial0 = i_nl[0] - delta0;
        let i_trial1 = i_nl[1] - delta1;
        let v_trial0 = p[0] + state.k[0][0] * i_trial0 + state.k[0][1] * i_trial1;
        let v_trial1 = p[1] + state.k[1][0] * i_trial0 + state.k[1][1] * i_trial1;
        let mut any_limited = false;
        let v_lim0 = pnjlim(v_trial0, v_d0, state.device_0_vt, DEVICE_0_VCRIT);
        let v_lim1 = pnjlim(v_trial1, v_d1, state.device_1_vt, DEVICE_1_VCRIT);
        let mut global_alpha = 1.0_f64;
        {
            let dv_full = v_trial0 - v_d0;
            let dv_lim = v_lim0 - v_d0;
            if dv_full.abs() > 1e-15 {
                let r = if dv_full * dv_lim < 0.0 {
                    0.0
                } else {
                    (dv_lim / dv_full).clamp(0.0, 1.0)
                };
                if r < global_alpha {
                    global_alpha = r;
                    any_limited = true;
                }
            }
        }
        {
            let dv_full = v_trial1 - v_d1;
            let dv_lim = v_lim1 - v_d1;
            if dv_full.abs() > 1e-15 {
                let r = if dv_full * dv_lim < 0.0 {
                    0.0
                } else {
                    (dv_lim / dv_full).clamp(0.0, 1.0)
                };
                if r < global_alpha {
                    global_alpha = r;
                    any_limited = true;
                }
            }
        }
        {
            let max_dv = ((v_trial0 - v_d0) * global_alpha)
                .abs()
                .max(((v_trial1 - v_d1) * global_alpha).abs());
            if max_dv > 3.500000 {
                global_alpha *= (3.500000 / max_dv).max(0.1);
                any_limited = true;
            }
        }
        i_nl[0] -= global_alpha * delta0;
        i_nl[1] -= global_alpha * delta1;

        // Convergence check (SPICE RELTOL=0.001, VNTOL=1e-6)
        if !any_limited {
            let mut nr_converged = true;
            {
                let dv = (v_trial0 - v_d0) * global_alpha;
                let threshold = 1e-3 * v_d0.abs().max((v_d0 + dv).abs()) + 1e-6;
                if dv.abs() > threshold {
                    nr_converged = false;
                }
            }
            {
                let dv = (v_trial1 - v_d1) * global_alpha;
                let threshold = 1e-3 * v_d1.abs().max((v_d1 + dv).abs()) + 1e-6;
                if dv.abs() > threshold {
                    nr_converged = false;
                }
            }
            if nr_converged {
                state.last_nr_iterations = iter as u32;
                converged = true;
                break;
            }
        }
    }

    // Step 5: Recover full node voltages: v = v_pred + S_NI * i_nl
    let mut v = v_pred;
    for i in 0..N {
        for j in 0..M {
            v[i] += state.s_ni[i][j] * i_nl[j];
        }
    }
    let converged = state.last_nr_iterations < MAX_ITER as u32;

    // Backward Euler fallback
    if !converged {
        state.diag_nr_max_iter_count += 1;
        state.diag_be_fallback_count += 1;

        // Rebuild RHS with backward Euler matrices
        let mut rhs_be = [0.0f64; N];
        for i in 0..N {
            let mut sum = RHS_CONST_BE[i];
            for j in 0..N {
                sum += state.a_neg_be[i][j] * state.v_prev[j];
            }
            for j in 0..M {
                sum += N_I[i][j] * state.i_nl_prev[j];
            }
            rhs_be[i] = sum;
        }
        rhs_be[INPUT_NODE] += input * input_conductance;

        // BE linear prediction: v_pred_be = S_be * rhs_be
        let mut v_pred_be = [0.0f64; N];
        for i in 0..N {
            let mut sum = 0.0;
            for j in 0..N {
                sum += state.s_be[i][j] * rhs_be[j];
            }
            v_pred_be[i] = sum;
        }

        let mut p_be = [0.0f64; M];
        for i in 0..M {
            let mut sum = 0.0;
            for j in 0..N {
                sum += N_V[i][j] * v_pred_be[j];
            }
            p_be[i] = sum;
        }

        // Reset i_nl to predictor for BE attempt
        for i in 0..M {
            i_nl[i] = 2.0 * state.i_nl_prev[i] - state.i_nl_prev_prev[i];
        }

        for _iter in 0..MAX_ITER {
            let v_d0 = p_be[0] + state.k_be[0][0] * i_nl[0] + state.k_be[0][1] * i_nl[1];
            let v_d1 = p_be[1] + state.k_be[1][0] * i_nl[0] + state.k_be[1][1] * i_nl[1];

            let vbe_0 = v_d0 * DEVICE_0_SIGN;
            let exp_be_0 = fast_exp(vbe_0 / (DEVICE_0_NF * state.device_0_vt));
            let i_dev0 = state.device_0_is * (exp_be_0 - 1.0) * DEVICE_0_SIGN;
            let jdev_0_0 = state.device_0_is / (DEVICE_0_NF * state.device_0_vt) * exp_be_0;
            let vbe_1 = v_d1 * DEVICE_1_SIGN;
            let exp_be_1 = fast_exp(vbe_1 / (DEVICE_1_NF * state.device_1_vt));
            let i_dev1 = state.device_1_is * (exp_be_1 - 1.0) * DEVICE_1_SIGN;
            let jdev_1_1 = state.device_1_is / (DEVICE_1_NF * state.device_1_vt) * exp_be_1;

            let f0 = i_nl[0] - i_dev0;
            let f1 = i_nl[1] - i_dev1;

            let j0_0 = 1.0 - jdev_0_0 * state.k_be[0][0];
            let j0_1 = 0.0 - jdev_0_0 * state.k_be[0][1];
            let j1_0 = 0.0 - jdev_1_1 * state.k_be[1][0];
            let j1_1 = 1.0 - jdev_1_1 * state.k_be[1][1];

            let det = j0_0 * j1_1 - j0_1 * j1_0;
            if det.abs() < 1e-15 {
                i_nl[0] -= (f0 * 0.5).clamp(-0.01, 0.01);
                i_nl[1] -= (f1 * 0.5).clamp(-0.01, 0.01);
                continue;
            }
            let inv_det = 1.0 / det;
            let delta0 = inv_det * (j1_1 * f0 - j0_1 * f1);
            let delta1 = inv_det * (-j1_0 * f0 + j0_0 * f1);
            let dv0 = -(state.k_be[0][0] * delta0 + state.k_be[0][1] * delta1);
            let dv1 = -(state.k_be[1][0] * delta0 + state.k_be[1][1] * delta1);
            let mut alpha = [1.0_f64; 2];
            let mut any_limited = false;
            if dv0.abs() > 1e-15 {
                let v_lim = pnjlim(v_d0 + dv0, v_d0, state.device_0_vt, DEVICE_0_VCRIT);
                let ratio = ((v_lim - v_d0) / dv0).max(0.01);
                if ratio < alpha[0] {
                    alpha[0] = ratio;
                    if ratio < 1.0 {
                        any_limited = true;
                    }
                }
            }
            if dv1.abs() > 1e-15 {
                let v_lim = pnjlim(v_d1 + dv1, v_d1, state.device_1_vt, DEVICE_1_VCRIT);
                let ratio = ((v_lim - v_d1) / dv1).max(0.01);
                if ratio < alpha[1] {
                    alpha[1] = ratio;
                    if ratio < 1.0 {
                        any_limited = true;
                    }
                }
            }
            // Global voltage backstop: limit max voltage change to 3.5V
            let max_dv = (dv0 * alpha[0]).abs().max((dv1 * alpha[1]).abs());
            if max_dv > 3.500000 {
                let factor = (3.500000 / max_dv).max(0.1);
                for a in alpha.iter_mut() {
                    *a *= factor;
                }
            }
            i_nl[0] -= alpha[0] * delta0;
            i_nl[1] -= alpha[1] * delta1;
            // Convergence check (SPICE RELTOL=0.001, VNTOL=1e-6)
            if !any_limited {
                let mut nr_converged = true;
                {
                    let step = dv0 * alpha[0];
                    let v_new = v_d0 + step;
                    let threshold = 1e-3 * v_d0.abs().max(v_new.abs()) + 1e-6;
                    if step.abs() > threshold {
                        nr_converged = false;
                    }
                }
                {
                    let step = dv1 * alpha[1];
                    let v_new = v_d1 + step;
                    let threshold = 1e-3 * v_d1.abs().max(v_new.abs()) + 1e-6;
                    if step.abs() > threshold {
                        nr_converged = false;
                    }
                }
                if nr_converged {
                    state.last_nr_iterations = _iter as u32;
                    break;
                }
            }
        }

        // Recover full v from BE solve
        v = v_pred_be;
        for i in 0..N {
            for j in 0..M {
                v[i] += state.s_ni_be[i][j] * i_nl[j];
            }
        }
    }

    // NaN/Inf check BEFORE state update — prevents corruption of v_prev/i_nl_prev.
    // Mirrors the DK-path reset in templates/rust/process_sample.rs.tera (Step 7).
    if !v.iter().all(|x| x.is_finite()) {
        state.v_prev = state.dc_operating_point;
        state.i_nl_prev = DC_NL_I;
        state.i_nl_prev_prev = DC_NL_I;
        state.input_prev = 0.0;
        state.diag_nan_reset_count += 1;
        let mut nan_out = [0.0f64; NUM_OUTPUTS];
        nan_out[0] = 4.26480459001615220e0;
        return nan_out;
    }

    // State update
    state.v_prev = v;
    state.i_nl_prev_prev = state.i_nl_prev;
    state.i_nl_prev = i_nl;

    // Extract outputs, DC blocking, and scaling
    let mut output = [0.0f64; NUM_OUTPUTS];
    for out_idx in 0..NUM_OUTPUTS {
        let raw_out = v[OUTPUT_NODES[out_idx]];
        let raw_out = if raw_out.is_finite() { raw_out } else { 0.0 };
        let scaled = raw_out * OUTPUT_SCALES[out_idx];
        let abs_out = scaled.abs();
        if abs_out > state.diag_peak_output {
            state.diag_peak_output = abs_out;
        }
        output[out_idx] = if scaled.is_finite() { scaled } else { 0.0 };
    }
    output
}
