// ============================================================================
// Generated by melange-solver
// Circuit: "* Wurlitzer 200A Tremolo Oscillator"
// ============================================================================

#![allow(clippy::excessive_precision)]
#![allow(dead_code)]

// =============================================================================
// CONSTANTS: Compile-time circuit topology (Nodal solver)
// =============================================================================

/// Number of augmented system nodes (including VS/VCVS/inductor branch variables)
pub const N: usize = 7;

/// Number of original circuit nodes (excluding ground)
pub const N_NODES: usize = 6;

/// Boundary between VS/VCVS rows and inductor branch variables
pub const N_AUG: usize = 7;

/// Total nonlinear dimension (sum of device dimensions)
pub const M: usize = 4;

/// Maximum NR iterations per sample
pub const MAX_ITER: usize = 200;

/// NR convergence tolerance (VNTOL)
pub const TOL: f64 = 1.00000000000000006e-9;

/// Default sample rate (Hz) used at code generation time.
pub const SAMPLE_RATE: f64 = 48000.0;

/// Oversampling factor (1 = none, 2 = 2x, 4 = 4x)
pub const OVERSAMPLING_FACTOR: usize = 1;

/// Input node index
pub const INPUT_NODE: usize = 5;

/// Number of output channels
pub const NUM_OUTPUTS: usize = 1;

/// Output node indices (one per output channel)
pub const OUTPUT_NODES: [usize; NUM_OUTPUTS] = [0];

/// Output scale factors (applied after DC blocking)
pub const OUTPUT_SCALES: [f64; NUM_OUTPUTS] = [1.00000000000000000e0];

/// Input resistance (Thevenin equivalent)
pub const INPUT_RESISTANCE: f64 = 1.00000000000000000e7;

/// G matrix: conductance matrix (sample-rate independent)
const G: [[f64; N]; N] = [
    [
        2.14236546682102636e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        3.70370380370370393e-5,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.94117747058823528e-6,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        2.94117747058823528e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.12865958446808507e-4,
        1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// C matrix: capacitance matrix (sample-rate independent)
const C: [[f64; N]; N] = [
    [
        1.20000999999999990e-7,
        -1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.19999999999999989e-7,
        2.39999999999999979e-7,
        -1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -1.19999999999999989e-7,
        1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.19999999999999989e-7,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A matrix: A = G + (2/T)*C (trapezoidal, at SAMPLE_RATE)
const A_DEFAULT: [[f64; N]; N] = [
    [
        1.17343325466821007e-2,
        -1.15199999999999990e-2,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        -1.15199999999999990e-2,
        2.30770370380370335e-2,
        -1.15199999999999990e-2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -1.15199999999999990e-2,
        1.15229411774705869e-2,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        1.15229411774705869e-2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.12865958446808507e-4,
        1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A_neg matrix: A_neg = (2/T)*C - G (trapezoidal history, at SAMPLE_RATE)
const A_NEG_DEFAULT: [[f64; N]; N] = [
    [
        1.13058594533178968e-2,
        -1.15199999999999990e-2,
        0.00000000000000000e0,
        1.47058823529411773e-6,
        0.00000000000000000e0,
        2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        -1.15199999999999990e-2,
        2.30029629619629625e-2,
        -1.15199999999999990e-2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -1.15199999999999990e-2,
        1.15170588225294111e-2,
        1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        1.47058823529411773e-6,
        0.00000000000000000e0,
        1.47058823529411773e-6,
        1.15170588225294111e-2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        -1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        -2.12865958446808507e-4,
        -1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A_be matrix: A_be = G + (1/T)*C (backward Euler, at SAMPLE_RATE)
const A_BE_DEFAULT: [[f64; N]; N] = [
    [
        5.97428454668210221e-3,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -2.12765957446808509e-4,
        0.00000000000000000e0,
    ],
    [
        -5.75999999999999950e-3,
        1.15570370380370362e-2,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -5.75999999999999950e-3,
        5.76294117747058743e-3,
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.47058823529411773e-6,
        0.00000000000000000e0,
        -1.47058823529411773e-6,
        5.76294117747058743e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000001000000001e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -2.12765957446808509e-4,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.12865958446808507e-4,
        1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// Default A_neg_be matrix: (1/T)*C (backward Euler history, at SAMPLE_RATE)
const A_NEG_BE_DEFAULT: [[f64; N]; N] = [
    [
        5.76004799999999938e-3,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -5.75999999999999950e-3,
        1.15199999999999990e-2,
        -5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -5.75999999999999950e-3,
        5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        5.75999999999999950e-3,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// N_v matrix: extracts controlling voltages from node voltages (M x N)
pub const N_V: [[f64; N]; M] = [
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
        -1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// N_i matrix: maps nonlinear currents to node injections (N x M)
pub const N_I: [[f64; M]; N] = [
    [
        -1.00000000000000000e0,
        0.00000000000000000e0,
        -1.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        -1.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        1.00000000000000000e0,
        1.00000000000000000e0,
        0.00000000000000000e0,
        -1.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
];

/// S matrix: A^{-1} (precomputed inverse, trapezoidal, at SAMPLE_RATE)
const S_DEFAULT: [[f64; N]; N] = [
    [
        3.93435898371326812e3,
        3.92075305545618494e3,
        3.91975242928666876e3,
        1.00236247540945600e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.37097656109206167e-1,
    ],
    [
        3.92075305545618539e3,
        3.99369954001274164e3,
        3.99268029555644671e3,
        1.00993329806599119e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.34202777756635316e-1,
    ],
    [
        3.91975242928666876e3,
        3.99268029555644671e3,
        4.07844471147694094e3,
        1.02075107714399671e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.33989878571631649e-1,
    ],
    [
        1.00236247540945578e0,
        1.00993329806599097e0,
        1.02075107714399671e0,
        8.67836570338633635e1,
        0.00000000000000000e0,
        0.00000000000000000e0,
        2.13268611789245910e-4,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        9.99999990000000071e3,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
    ],
    [
        8.37097656109206056e-1,
        8.34202777756635205e-1,
        8.33989878571631649e-1,
        2.13268611789245910e-4,
        0.00000000000000000e0,
        1.00000000000000000e0,
        -3.47600741682540368e-5,
    ],
];

/// K matrix: N_v * S * N_i (nonlinear kernel, trapezoidal, at SAMPLE_RATE)
const K_DEFAULT: [[f64; M]; M] = [
    [
        -1.39197523292866699e4,
        -1.40784446114769416e4,
        -3.91975242928666876e3,
        9.99999990000000071e3,
    ],
    [
        1.46065544265993594e1,
        -1.58692282190272181e2,
        1.46065544265993594e1,
        0.00000000000000000e0,
    ],
    [
        9.99999990000000071e3,
        9.99999990000000071e3,
        0.00000000000000000e0,
        -9.99999990000000071e3,
    ],
    [
        1.39343588837132684e4,
        1.39197523292866699e4,
        3.93435898371326812e3,
        -9.99999990000000071e3,
    ],
];

/// S_NI matrix: S * N_i (precomputed for final voltage recovery, N x M)
const S_NI_DEFAULT: [[f64; M]; N] = [
    [
        -3.93435898371326812e3,
        -3.91975242928666876e3,
        -3.93435898371326812e3,
        0.00000000000000000e0,
    ],
    [
        -3.92075305545618539e3,
        -3.99268029555644671e3,
        -3.92075305545618539e3,
        0.00000000000000000e0,
    ],
    [
        -3.91975242928666876e3,
        -4.07844471147694094e3,
        -3.91975242928666876e3,
        0.00000000000000000e0,
    ],
    [
        -1.00236247540945578e0,
        -1.02075107714399671e0,
        -1.00236247540945578e0,
        0.00000000000000000e0,
    ],
    [
        9.99999990000000071e3,
        9.99999990000000071e3,
        0.00000000000000000e0,
        -9.99999990000000071e3,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -8.37097656109206056e-1,
        -8.33989878571631649e-1,
        -8.37097656109206056e-1,
        0.00000000000000000e0,
    ],
];

/// S_be matrix: A_be^{-1} (backward Euler, at SAMPLE_RATE)
const S_BE_DEFAULT: [[f64; N]; N] = [
    [
        3.93725233914840283e3,
        3.91011508022033013e3,
        3.90812002284700020e3,
        2.00198335220834345e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.37713263648596551e-1,
    ],
    [
        3.91011508022033013e3,
        4.05557935955550010e3,
        4.05351007066186457e3,
        2.03215911745951017e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.31939378770283122e-1,
    ],
    [
        3.90812002284699929e3,
        4.05351007066186412e3,
        4.22496435574593397e3,
        2.07540174981669434e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        8.31514898478085018e-1,
    ],
    [
        2.00198335220834300e0,
        2.03215911745951017e0,
        2.07540174981669434e0,
        1.73523547327525279e2,
        0.00000000000000000e0,
        0.00000000000000000e0,
        4.25953904725179396e-4,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        9.99999990000000071e3,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        1.00000000000000000e0,
    ],
    [
        8.37713263648596329e-1,
        8.31939378770282900e-1,
        8.31514898478084796e-1,
        4.25953904725179342e-4,
        0.00000000000000000e0,
        1.00000000000000000e0,
        -3.46290938407241690e-5,
    ],
];

/// K_be matrix: N_v * S_be * N_i (backward Euler kernel)
const K_BE_DEFAULT: [[f64; M]; M] = [
    [
        -1.39081199228469995e4,
        -1.42249642557459338e4,
        -3.90812002284699929e3,
        9.99999990000000071e3,
    ],
    [
        2.91323163014035345e1,
        -3.16844332898933772e2,
        2.91323163014035345e1,
        0.00000000000000000e0,
    ],
    [
        9.99999990000000071e3,
        9.99999990000000071e3,
        0.00000000000000000e0,
        -9.99999990000000071e3,
    ],
    [
        1.39372522391484035e4,
        1.39081199228470014e4,
        3.93725233914840283e3,
        -9.99999990000000071e3,
    ],
];

/// S_NI_be matrix: S_be * N_i (backward Euler, for final voltage recovery)
const S_NI_BE_DEFAULT: [[f64; M]; N] = [
    [
        -3.93725233914840283e3,
        -3.90812002284700020e3,
        -3.93725233914840283e3,
        0.00000000000000000e0,
    ],
    [
        -3.91011508022033013e3,
        -4.05351007066186457e3,
        -3.91011508022033013e3,
        0.00000000000000000e0,
    ],
    [
        -3.90812002284699929e3,
        -4.22496435574593397e3,
        -3.90812002284699929e3,
        0.00000000000000000e0,
    ],
    [
        -2.00198335220834300e0,
        -2.07540174981669434e0,
        -2.00198335220834300e0,
        0.00000000000000000e0,
    ],
    [
        9.99999990000000071e3,
        9.99999990000000071e3,
        0.00000000000000000e0,
        -9.99999990000000071e3,
    ],
    [
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
        0.00000000000000000e0,
    ],
    [
        -8.37713263648596329e-1,
        -8.31514898478084796e-1,
        -8.37713263648596329e-1,
        0.00000000000000000e0,
    ],
];

/// RHS constant contribution from DC sources (trapezoidal: node rows x2, VS rows x1)
pub const RHS_CONST: [f64; N] = [
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    1.50000000000000000e1,
];

/// RHS constant contribution from DC sources (backward Euler: all rows x1)
pub const RHS_CONST_BE: [f64; N] = [
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    0.00000000000000000e0,
    1.50000000000000000e1,
];

/// Whether the nonlinear DC OP solver converged at codegen time
pub const DC_OP_CONVERGED: bool = true;

// =============================================================================
// DEVICE MODELS
// =============================================================================

const DEVICE_0_IS: f64 = 1.40000000000000003e-14;
const DEVICE_0_VT: f64 = 2.58519910000000012e-2;
const DEVICE_0_BETA_F: f64 = 2.00000000000000000e2;
const DEVICE_0_BETA_R: f64 = 3.00000000000000000e0;
const DEVICE_0_NF: f64 = 1.00000000000000000e0;
const DEVICE_0_NR: f64 = 1.00000000000000000e0;
const DEVICE_0_ISE: f64 = 0.00000000000000000e0;
const DEVICE_0_NE: f64 = 1.50000000000000000e0;
const DEVICE_0_ISC: f64 = 0.00000000000000000e0;
const DEVICE_0_NC: f64 = 2.00000000000000000e0;
const DEVICE_0_SIGN: f64 = 1.0;
const DEVICE_0_USE_GP: bool = false;
const DEVICE_0_VAF: f64 = f64::INFINITY;
const DEVICE_0_VAR: f64 = f64::INFINITY;
const DEVICE_0_IKF: f64 = f64::INFINITY;
const DEVICE_0_IKR: f64 = f64::INFINITY;
const DEVICE_0_VCRIT: f64 = 7.21213101001093038e-1;

const DEVICE_1_IS: f64 = 1.40000000000000003e-14;
const DEVICE_1_VT: f64 = 2.58519910000000012e-2;
const DEVICE_1_BETA_F: f64 = 2.00000000000000000e2;
const DEVICE_1_BETA_R: f64 = 3.00000000000000000e0;
const DEVICE_1_NF: f64 = 1.00000000000000000e0;
const DEVICE_1_NR: f64 = 1.00000000000000000e0;
const DEVICE_1_ISE: f64 = 0.00000000000000000e0;
const DEVICE_1_NE: f64 = 1.50000000000000000e0;
const DEVICE_1_ISC: f64 = 0.00000000000000000e0;
const DEVICE_1_NC: f64 = 2.00000000000000000e0;
const DEVICE_1_SIGN: f64 = 1.0;
const DEVICE_1_USE_GP: bool = false;
const DEVICE_1_VAF: f64 = f64::INFINITY;
const DEVICE_1_VAR: f64 = f64::INFINITY;
const DEVICE_1_IKF: f64 = f64::INFINITY;
const DEVICE_1_IKR: f64 = f64::INFINITY;
const DEVICE_1_VCRIT: f64 = 7.21213101001093038e-1;

/// Fast exp() for audio circuit simulation.
/// Input clamped to [-40, 40] (matches melange safe_exp convention).
///
/// Default: polynomial approximation (<0.0004% error, ~6x faster than libm).
/// To use hardware/libm exp, compile with: `--cfg melange_precise_exp`
#[inline(always)]
fn fast_exp(x: f64) -> f64 {
    #[cfg(melange_precise_exp)]
    {
        x.clamp(-40.0, 40.0).exp()
    }
    #[cfg(not(melange_precise_exp))]
    {
        // Range reduction + 5th-order minimax polynomial. <0.0004% max relative error.
        // No lookup tables, no libm dependency, branchless hot path.
        let x = x.clamp(-40.0, 40.0);
        const LN2_INV: f64 = 1.4426950408889634;
        const LN2_HI: f64 = 0.6931471803691238;
        const LN2_LO: f64 = 1.9082149292705877e-10;
        const SHIFT: f64 = 6755399441055744.0; // 2^52 + 2^51
        let z = x * LN2_INV + SHIFT;
        let n_i64 = z.to_bits() as i64 - SHIFT.to_bits() as i64;
        let n = n_i64 as f64;
        let f = (x - n * LN2_HI) - n * LN2_LO;
        let p = 1.0
            + f * (1.0
                + f * (0.5
                    + f * (0.16666666666666607
                        + f * (0.04166666666665876 + f * 0.008333333333492337))));
        let pow2n = f64::from_bits(((1023 + n_i64) as u64) << 52);
        p * pow2n
    }
}

/// Fast ln() for audio circuit simulation.
/// Symmetric log series (~0.005% max relative error, ~3x faster than libm).
/// Only valid for positive inputs.
#[inline(always)]
fn fast_ln(x: f64) -> f64 {
    #[cfg(melange_precise_exp)]
    {
        x.ln()
    }
    #[cfg(not(melange_precise_exp))]
    {
        // Extract exponent and mantissa from IEEE 754 double
        let bits = x.to_bits();
        let e = ((bits >> 52) & 0x7FF) as i64 - 1023;
        // Normalize mantissa to [1, 2)
        let m_bits = (bits & 0x000F_FFFF_FFFF_FFFF) | 0x3FF0_0000_0000_0000;
        let m = f64::from_bits(m_bits);
        // Symmetric log series: u = (m-1)/(m+1), ln(m) = 2u(1 + u²/3 + u⁴/5 + u⁶/7)
        // For m in [1,2), u in [0,1/3): converges much faster than Taylor.
        let u = (m - 1.0) / (m + 1.0);
        let u2 = u * u;
        let ln_m =
            2.0 * u * (1.0 + u2 * (0.3333333333333333 + u2 * (0.2 + u2 * 0.14285714285714285)));
        ln_m + (e as f64) * 0.6931471805599453 // e * ln(2)
    }
}

// Canonical source: melange-primitives/src/nr.rs (pnjlim, fetlim)
// Duplicated here because generated code must be self-contained.

/// SPICE PN junction voltage limiting (from SPICE3f5 DEVpnjlim).
///
/// Limits large forward voltage steps on exponential I-V curves using
/// logarithmic compression. Only activates when vnew > vcrit with large step.
#[inline(always)]
fn pnjlim(vnew: f64, vold: f64, vt: f64, vcrit: f64) -> f64 {
    if vnew > vcrit && (vnew - vold).abs() > vt + vt {
        if vold >= 0.0 {
            let arg = 1.0 + (vnew - vold) / vt;
            if arg > 0.0 {
                vold + vt * arg.ln()
            } else {
                vcrit
            }
        } else {
            vt * (vnew / vt).ln()
        }
    } else {
        vnew
    }
}

/// SPICE FET voltage limiting (from SPICE3f5 DEVfetlim).
///
/// Prevents gate-source voltage from jumping across threshold boundary.
/// The allowed step size adapts to the distance from threshold.
#[inline(always)]
fn fetlim(vnew: f64, vold: f64, vto: f64) -> f64 {
    let delv = vnew - vold;
    let vtox = vto + 3.5;
    let vtsthi = (2.0 * (vold - vto)).abs() + 2.0;
    let vtstlo = vtsthi / 2.0 + 2.0;

    if vold >= vto {
        // Device is "on"
        if vold >= vtox {
            if delv <= 0.0 {
                // Going off
                if vnew >= vtox {
                    if -delv > vtstlo {
                        return vold - vtstlo;
                    }
                } else {
                    return vnew.max(vto + 2.0);
                }
            } else {
                // Staying on
                if delv >= vtsthi {
                    return vold + vtsthi;
                }
            }
        } else {
            // Middle region
            if delv <= 0.0 {
                return vnew.max(vto - 0.5);
            } else {
                return vnew.min(vto + 4.0);
            }
        }
    } else {
        // Device is "off"
        if delv <= 0.0 {
            if -delv > vtstlo {
                return vold - vtstlo;
            }
        } else if vnew <= vto + 0.5 {
            if delv > vtstlo {
                return vold + vtstlo;
            }
        } else {
            return vto + 0.5;
        }
    }
    vnew
}

// Canonical source: melange-devices/src/bjt.rs (BjtEbersMoll, BjtGummelPoon)
// Duplicated here because generated code must be self-contained.

/// Safe exponential using fast_exp (clamp to prevent overflow, matches runtime [-40, 40] range)
#[inline(always)]
fn safe_exp(x: f64) -> f64 {
    fast_exp(x)
}

/// Gummel-Poon base charge factor qb.
///
/// Accounts for Early effect (VAF/VAR) and high-level injection (IKF).
/// When use_gp=false or all GP params are infinite, returns 1.0 (Ebers-Moll).
/// nf: forward emission coefficient (uses NF*VT for forward exponential).
/// nr: reverse emission coefficient (uses NR*VT for reverse exponential).
#[inline(always)]
fn bjt_qb(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
) -> f64 {
    if !use_gp {
        return 1.0;
    }
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;

    // Early effect: q1 = 1 / (1 - Vbe/VAR - Vbc/VAF)
    let q1_denom = 1.0 - vbe_eff / var - vbc_eff / vaf;
    if q1_denom.abs() < 1e-30 {
        return 1.0;
    }
    let q1 = 1.0 / q1_denom;

    // High-level injection: q2 = Is*exp(Vbe/(NF*Vt))/IKF + Is*exp(Vbc/(NR*Vt))/IKR
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);
    let q2 = is * exp_be / ikf + is * exp_bc / ikr;

    q1 * (1.0 + (1.0 + 4.0 * q2).max(0.0).sqrt()) / 2.0
}

/// BJT collector current Ic(Vbe, Vbc)
/// sign: +1.0 for NPN, -1.0 for PNP (applied to voltages and output current)
/// nf: forward emission coefficient. Transport current uses exp(Vbe/(NF*VT)).
/// nr: reverse emission coefficient. Reverse current uses exp(Vbc/(NR*VT)).
/// When use_gp=true, divides transport current by qb (Gummel-Poon).
#[inline(always)]
fn bjt_ic(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
) -> f64 {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);
    let i_cc = is * (exp_be - exp_bc);
    let qb = bjt_qb(vbe, vbc, is, vt, nf, nr, sign, use_gp, vaf, var, ikf, ikr);
    sign * (i_cc / qb - is / beta_r * (exp_bc - 1.0))
}

/// BJT base current Ib(Vbe, Vbc)
/// sign: +1.0 for NPN, -1.0 for PNP
/// nf: forward emission coefficient for ideal base current.
/// nr: reverse emission coefficient for reverse base current.
/// ise, ne: B-E leakage saturation current and emission coefficient.
/// isc, nc: B-C leakage saturation current and emission coefficient.
/// When use_gp=true, forward ideal component (Is/BF) is divided by qb.
/// Reverse component and ISE/ISC leakage are unchanged.
#[inline(always)]
fn bjt_ib(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
) -> f64 {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);
    // Forward ideal component: Is/BF * (exp(Vbe/(NF*VT)) - 1)
    let ib_fwd = is / beta_f * (exp_be - 1.0);
    let ib_rev = is / beta_r * (exp_bc - 1.0);
    let mut ib = if use_gp {
        let qb = bjt_qb(vbe, vbc, is, vt, nf, nr, sign, true, vaf, var, ikf, ikr);
        ib_fwd / qb + ib_rev
    } else {
        ib_fwd + ib_rev
    };
    // B-E leakage current: ISE * (exp(Vbe/(NE*VT)) - 1) (unaffected by GP)
    if ise > 0.0 {
        let ne_vt = ne * vt;
        let exp_be_leak = safe_exp(vbe_eff / ne_vt);
        ib += ise * (exp_be_leak - 1.0);
    }
    // B-C leakage current: ISC * (exp(Vbc/(NC*VT)) - 1) (unaffected by GP)
    if isc > 0.0 {
        let nc_vt = nc * vt;
        let exp_bc_leak = safe_exp(vbc_eff / nc_vt);
        ib += isc * (exp_bc_leak - 1.0);
    }
    sign * ib
}

/// BJT Jacobian: [dIc/dVbe, dIc/dVbc, dIb/dVbe, dIb/dVbc]
/// sign: +1.0 for NPN, -1.0 for PNP (s*s=1, so Jacobian entries are polarity-invariant)
/// nf: forward emission coefficient. nr: reverse emission coefficient.
/// ise, ne: B-E leakage. isc, nc: B-C leakage.
/// When use_gp=true, uses quotient rule for d(Icc/qb)/dV (Gummel-Poon).
#[inline(always)]
fn bjt_jacobian(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
) -> [f64; 4] {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);

    // Base current Jacobian (EM components — may be adjusted for GP below)
    let dib_fwd_dvbe = (is / (beta_f * nf_vt)) * exp_be;
    let dib_rev_dvbc = (is / (beta_r * nr_vt)) * exp_bc;
    let mut dib_leak_dvbe = 0.0;
    let mut dib_leak_dvbc = 0.0;
    // ISE leakage contribution to dIb/dVbe
    if ise > 0.0 {
        let ne_vt = ne * vt;
        let exp_be_leak = safe_exp(vbe_eff / ne_vt);
        dib_leak_dvbe = (ise / ne_vt) * exp_be_leak;
    }
    // ISC leakage contribution to dIb/dVbc
    if isc > 0.0 {
        let nc_vt = nc * vt;
        let exp_bc_leak = safe_exp(vbc_eff / nc_vt);
        dib_leak_dvbc = (isc / nc_vt) * exp_bc_leak;
    }

    if !use_gp {
        // Ebers-Moll: simple derivatives
        let dic_dvbe = is / nf_vt * exp_be;
        let dic_dvbc = -(is / nr_vt) * exp_bc - (is / (beta_r * nr_vt)) * exp_bc;
        return [
            dic_dvbe,
            dic_dvbc,
            dib_fwd_dvbe + dib_leak_dvbe,
            dib_rev_dvbc + dib_leak_dvbc,
        ];
    }

    // Gummel-Poon: quotient rule for d(Icc/qb)/dV
    let icc = is * (exp_be - exp_bc);
    let dicc_dvbe = is / nf_vt * exp_be;
    let dicc_dvbc = -is / nr_vt * exp_bc;

    // q1 and derivatives
    let q1_denom = 1.0 - vbe_eff / var - vbc_eff / vaf;
    let (q1, dq1_dvbe, dq1_dvbc) = if q1_denom.abs() < 1e-30 {
        (1.0, 0.0, 0.0)
    } else {
        let q1 = 1.0 / q1_denom;
        (q1, q1 * q1 / var, q1 * q1 / vaf)
    };

    // q2 and derivatives: q2 = Is*exp(Vbe/(NF*Vt))/IKF + Is*exp(Vbc/(NR*Vt))/IKR
    let q2 = is * exp_be / ikf + is * exp_bc / ikr;
    let dq2_dvbe = is / (nf_vt * ikf) * exp_be;
    let dq2_dvbc = is / (nr_vt * ikr) * exp_bc;

    // Discriminant D = sqrt(1 + 4*q2)
    let disc = (1.0 + 4.0 * q2).max(0.0);
    let d = disc.sqrt();
    let dd_dvbe = if d > 1e-15 { 2.0 * dq2_dvbe / d } else { 0.0 };
    let dd_dvbc = if d > 1e-15 { 2.0 * dq2_dvbc / d } else { 0.0 };

    // qb = q1 * (1 + D) / 2
    let qb = q1 * (1.0 + d) / 2.0;
    let dqb_dvbe = dq1_dvbe * (1.0 + d) / 2.0 + q1 * dd_dvbe / 2.0;
    let dqb_dvbc = dq1_dvbc * (1.0 + d) / 2.0 + q1 * dd_dvbc / 2.0;

    // Quotient rule: d(Icc/qb)/dV = (dIcc/dV * qb - Icc * dqb/dV) / qb^2
    let qb2 = (qb * qb).max(1e-30);
    let quotient_dvbe = (dicc_dvbe * qb - icc * dqb_dvbe) / qb2;
    let quotient_dvbc = (dicc_dvbc * qb - icc * dqb_dvbc) / qb2;

    let d_bc_term_dvbc = is / (beta_r * nr_vt) * exp_bc;

    // GP base current Jacobian: forward ideal component (Is/BF*(exp_be-1)) / qb
    let ib_fwd = is / beta_f * (exp_be - 1.0);
    let dib_fwd_gp_dvbe = (dib_fwd_dvbe * qb - ib_fwd * dqb_dvbe) / qb2;
    let dib_fwd_gp_dvbc = -ib_fwd * dqb_dvbc / qb2;

    [
        quotient_dvbe,
        quotient_dvbc - d_bc_term_dvbc,
        dib_fwd_gp_dvbe + dib_leak_dvbe,
        dib_fwd_gp_dvbc + dib_rev_dvbc + dib_leak_dvbc,
    ]
}

/// Combined BJT evaluation: returns (Ic, Ib, [dIc/dVbe, dIc/dVbc, dIb/dVbe, dIb/dVbc]).
///
/// Computes exp(Vbe/(NF*VT)) and exp(Vbc/(NR*VT)) once and shares them across current
/// and Jacobian calculations. Reduces from 8-10 exp() to 2-4 per evaluation.
#[inline(always)]
fn bjt_evaluate(
    vbe: f64,
    vbc: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
) -> (f64, f64, [f64; 4]) {
    let vbe_eff = sign * vbe;
    let vbc_eff = sign * vbc;
    let nf_vt = nf * vt;
    let nr_vt = nr * vt;

    // Shared exponentials (computed once)
    let exp_be = safe_exp(vbe_eff / nf_vt);
    let exp_bc = safe_exp(vbc_eff / nr_vt);

    // ISE leakage exponential (computed once, only when needed)
    let exp_be_leak = if ise > 0.0 {
        safe_exp(vbe_eff / (ne * vt))
    } else {
        0.0
    };

    // ISC leakage exponential (computed once, only when needed)
    let exp_bc_leak = if isc > 0.0 {
        safe_exp(vbc_eff / (nc * vt))
    } else {
        0.0
    };

    // === Collector current ===
    let i_cc = is * (exp_be - exp_bc);

    // === Base current components ===
    let ib_fwd = is / beta_f * (exp_be - 1.0);
    let ib_rev = is / beta_r * (exp_bc - 1.0);
    let ib_leak_be = if ise > 0.0 {
        ise * (exp_be_leak - 1.0)
    } else {
        0.0
    };
    let ib_leak_bc = if isc > 0.0 {
        isc * (exp_bc_leak - 1.0)
    } else {
        0.0
    };

    // === Base current Jacobian (EM components) ===
    let dib_fwd_dvbe = (is / (beta_f * nf_vt)) * exp_be;
    let dib_rev_dvbc = (is / (beta_r * nr_vt)) * exp_bc;
    let dib_leak_dvbe = if ise > 0.0 {
        (ise / (ne * vt)) * exp_be_leak
    } else {
        0.0
    };
    let dib_leak_dvbc = if isc > 0.0 {
        (isc / (nc * vt)) * exp_bc_leak
    } else {
        0.0
    };

    if !use_gp {
        // Ebers-Moll
        let ic = sign * (i_cc - is / beta_r * (exp_bc - 1.0));
        let ib = sign * (ib_fwd + ib_rev + ib_leak_be + ib_leak_bc);
        let dic_dvbe = is / nf_vt * exp_be;
        let dic_dvbc = -(is / nr_vt) * exp_bc - (is / (beta_r * nr_vt)) * exp_bc;
        return (
            ic,
            ib,
            [
                dic_dvbe,
                dic_dvbc,
                dib_fwd_dvbe + dib_leak_dvbe,
                dib_rev_dvbc + dib_leak_dvbc,
            ],
        );
    }

    // Gummel-Poon
    // q1 and derivatives
    let q1_denom = 1.0 - vbe_eff / var - vbc_eff / vaf;
    let (q1, dq1_dvbe, dq1_dvbc) = if q1_denom.abs() < 1e-30 {
        (1.0, 0.0, 0.0)
    } else {
        let q1 = 1.0 / q1_denom;
        (q1, q1 * q1 / var, q1 * q1 / vaf)
    };

    // q2 and derivatives (uses shared exp_be, exp_bc)
    let q2 = is * exp_be / ikf + is * exp_bc / ikr;
    let dq2_dvbe = is / (nf_vt * ikf) * exp_be;
    let dq2_dvbc = is / (nr_vt * ikr) * exp_bc;

    // Discriminant D = sqrt(1 + 4*q2)
    let disc = (1.0 + 4.0 * q2).max(0.0);
    let d = disc.sqrt();
    let dd_dvbe = if d > 1e-15 { 2.0 * dq2_dvbe / d } else { 0.0 };
    let dd_dvbc = if d > 1e-15 { 2.0 * dq2_dvbc / d } else { 0.0 };

    // qb = q1 * (1 + D) / 2
    let qb = q1 * (1.0 + d) / 2.0;
    let dqb_dvbe = dq1_dvbe * (1.0 + d) / 2.0 + q1 * dd_dvbe / 2.0;
    let dqb_dvbc = dq1_dvbc * (1.0 + d) / 2.0 + q1 * dd_dvbc / 2.0;

    let ic = sign * (i_cc / qb - is / beta_r * (exp_bc - 1.0));
    // GP: forward ideal component divided by qb
    let ib = sign * (ib_fwd / qb + ib_rev + ib_leak_be + ib_leak_bc);

    // Quotient rule: d(Icc/qb)/dV = (dIcc/dV * qb - Icc * dqb/dV) / qb^2
    let dicc_dvbe = is / nf_vt * exp_be;
    let dicc_dvbc = -is / nr_vt * exp_bc;
    let qb2 = (qb * qb).max(1e-30);
    let quotient_dvbe = (dicc_dvbe * qb - i_cc * dqb_dvbe) / qb2;
    let quotient_dvbc = (dicc_dvbc * qb - i_cc * dqb_dvbc) / qb2;
    let d_bc_term_dvbc = is / (beta_r * nr_vt) * exp_bc;

    // GP base current Jacobian: forward ideal component / qb
    let dib_fwd_gp_dvbe = (dib_fwd_dvbe * qb - ib_fwd * dqb_dvbe) / qb2;
    let dib_fwd_gp_dvbc = -ib_fwd * dqb_dvbc / qb2;

    (
        ic,
        ib,
        [
            quotient_dvbe,
            quotient_dvbc - d_bc_term_dvbc,
            dib_fwd_gp_dvbe + dib_leak_dvbe,
            dib_fwd_gp_dvbc + dib_rev_dvbc + dib_leak_dvbc,
        ],
    )
}

/// BJT with parasitic resistances (RB, RC, RE).
///
/// Given external junction voltages (Vbe_ext, Vbc_ext), solves for internal
/// junction voltages via inner 2D Newton-Raphson, then returns:
///   (Ic, Ib, [dIc/dVbe_ext, dIc/dVbc_ext, dIb/dVbe_ext, dIb/dVbc_ext])
///
/// The inner NR solves: find (Vbe_int, Vbc_int) such that
///   F1 = Vbe_int - Vbe_ext + Ib*RB + (Ic+Ib)*RE = 0
///   F2 = Vbc_int - Vbc_ext + Ib*RB - Ic*RC = 0
/// (note: RE term uses Ie = -(Ic+Ib), so V_E_int = V_E_ext - Ie*RE = V_E_ext + (Ic+Ib)*RE)
///
/// When RB=RC=RE=0, this reduces to direct evaluation (no inner loop).
#[inline(always)]
fn bjt_with_parasitics(
    vbe_ext: f64,
    vbc_ext: f64,
    is: f64,
    vt: f64,
    nf: f64,
    nr: f64,
    beta_f: f64,
    beta_r: f64,
    sign: f64,
    use_gp: bool,
    vaf: f64,
    var: f64,
    ikf: f64,
    ikr: f64,
    ise: f64,
    ne: f64,
    isc: f64,
    nc: f64,
    rb: f64,
    rc: f64,
    re: f64,
) -> (f64, f64, [f64; 4]) {
    const INNER_MAX_ITER: usize = 15;
    const INNER_TOL: f64 = 1e-10;

    // Initial guess: internal = external
    let mut vbe_int = vbe_ext;
    let mut vbc_int = vbc_ext;

    for _iter in 0..INNER_MAX_ITER {
        let (ic, ib, jac_int) = bjt_evaluate(
            vbe_int, vbc_int, is, vt, nf, nr, beta_f, beta_r, sign, use_gp, vaf, var, ikf, ikr,
            ise, ne, isc, nc,
        );
        let dic_dvbe = jac_int[0];
        let dic_dvbc = jac_int[1];
        let dib_dvbe = jac_int[2];
        let dib_dvbc = jac_int[3];

        // Residuals
        let f1 = vbe_int - vbe_ext + ib * rb + (ic + ib) * re;
        let f2 = vbc_int - vbc_ext + ib * rb - ic * rc;

        if f1.abs() < INNER_TOL && f2.abs() < INNER_TOL {
            break;
        }

        // Jacobian of F w.r.t. (Vbe_int, Vbc_int)
        let j11 = 1.0 + dib_dvbe * rb + (dic_dvbe + dib_dvbe) * re;
        let j12 = dib_dvbc * rb + (dic_dvbc + dib_dvbc) * re;
        let j21 = dib_dvbe * rb - dic_dvbe * rc;
        let j22 = 1.0 + dib_dvbc * rb - dic_dvbc * rc;

        // Solve 2x2 via Cramer's rule
        let det = j11 * j22 - j12 * j21;
        if det.abs() < 1e-30 {
            break;
        }
        let inv_det = 1.0 / det;
        let dvbe = (j22 * f1 - j12 * f2) * inv_det;
        let dvbc = (j11 * f2 - j21 * f1) * inv_det;

        // Step limiting: max ±4*VT per iteration
        let max_step = 4.0 * vt;
        let dvbe = dvbe.clamp(-max_step, max_step);
        let dvbc = dvbc.clamp(-max_step, max_step);

        vbe_int -= dvbe;
        vbc_int -= dvbc;
    }

    // Final evaluation at converged internal voltages
    let (ic, ib, jac_int) = bjt_evaluate(
        vbe_int, vbc_int, is, vt, nf, nr, beta_f, beta_r, sign, use_gp, vaf, var, ikf, ikr, ise,
        ne, isc, nc,
    );

    // External Jacobian: J_ext = J_device * J_F^{-1}
    // J_F = [[j11, j12], [j21, j22]] (recompute at converged point)
    let dic_dvbe = jac_int[0];
    let dic_dvbc = jac_int[1];
    let dib_dvbe = jac_int[2];
    let dib_dvbc = jac_int[3];

    let j11 = 1.0 + dib_dvbe * rb + (dic_dvbe + dib_dvbe) * re;
    let j12 = dib_dvbc * rb + (dic_dvbc + dib_dvbc) * re;
    let j21 = dib_dvbe * rb - dic_dvbe * rc;
    let j22 = 1.0 + dib_dvbc * rb - dic_dvbc * rc;

    let det = j11 * j22 - j12 * j21;
    if det.abs() < 1e-30 {
        // Fallback: return intrinsic Jacobian
        return (ic, ib, jac_int);
    }
    let inv_det = 1.0 / det;

    // J_F^{-1} = [[j22, -j12], [-j21, j11]] / det
    let fi11 = j22 * inv_det;
    let fi12 = -j12 * inv_det;
    let fi21 = -j21 * inv_det;
    let fi22 = j11 * inv_det;

    // J_ext = J_device * J_F^{-1}
    let dic_dvbe_ext = dic_dvbe * fi11 + dic_dvbc * fi21;
    let dic_dvbc_ext = dic_dvbe * fi12 + dic_dvbc * fi22;
    let dib_dvbe_ext = dib_dvbe * fi11 + dib_dvbc * fi21;
    let dib_dvbc_ext = dib_dvbe * fi12 + dib_dvbc * fi22;

    (
        ic,
        ib,
        [dic_dvbe_ext, dic_dvbc_ext, dib_dvbe_ext, dib_dvbc_ext],
    )
}

// =============================================================================
// STATE STRUCTURE (Nodal solver)
// =============================================================================

/// DC operating point: steady-state node voltages
pub const DC_OP: [f64; N] = [
    4.26487382569817974e0,
    0.00000000000000000e0,
    1.24643449212847934e0,
    2.75565322199124418e0,
    6.66528752563515625e-1,
    1.50000000000000000e1,
    -2.28706941378761840e-3,
];

/// DC operating point: nonlinear device currents at bias point
pub const DC_NL_I: [f64; M] = [
    7.72892333516560844e-5,
    3.86446161998280494e-7,
    2.20456071910682351e-3,
    1.10228035907741172e-5,
];

/// Circuit state for one processing channel (nodal solver).
///
/// Contains per-sample state and sample-rate-dependent matrices.
/// Call [`set_sample_rate`](CircuitState::set_sample_rate) before processing
/// if the host sample rate differs from [`SAMPLE_RATE`].
#[derive(Clone, Debug)]
pub struct CircuitState {
    /// Previous node voltages v[n-1]
    pub v_prev: [f64; N],

    /// Previous nonlinear currents i_nl[n-1]
    pub i_nl_prev: [f64; M],

    /// Nonlinear currents from two samples ago i_nl[n-2] (for NR predictor)
    pub i_nl_prev_prev: [f64; M],

    /// DC operating point (for reset/sleep/wake)
    pub dc_operating_point: [f64; N],

    /// Previous input sample for trapezoidal integration
    pub input_prev: f64,

    /// Iteration count from last solve (for diagnostics)
    pub last_nr_iterations: u32,

    /// Diagnostic: peak absolute output (pre-clamp)
    pub diag_peak_output: f64,
    /// Diagnostic: number of times output exceeded +/-10V
    pub diag_clamp_count: u64,
    /// Diagnostic: number of times NR hit max iterations
    pub diag_nr_max_iter_count: u64,
    /// Diagnostic: number of backward Euler fallback activations
    pub diag_be_fallback_count: u64,
    /// Diagnostic: number of times NaN triggered state reset
    pub diag_nan_reset_count: u64,

    /// A matrix: G + alpha*C (trapezoidal), recomputed by set_sample_rate
    pub a: [[f64; N]; N],
    /// A_neg matrix: alpha*C - G (trapezoidal history), recomputed by set_sample_rate
    pub a_neg: [[f64; N]; N],
    /// A_be matrix: G + (1/T)*C (backward Euler), recomputed by set_sample_rate
    pub a_be: [[f64; N]; N],
    /// A_neg_be matrix: (1/T)*C (backward Euler history), recomputed by set_sample_rate
    pub a_neg_be: [[f64; N]; N],
    /// S matrix: A^{-1} (trapezoidal), recomputed by set_sample_rate
    pub s: [[f64; N]; N],
    /// K matrix: N_v * S * N_i (nonlinear kernel), recomputed by set_sample_rate
    pub k: [[f64; M]; M],
    /// S_NI matrix: S * N_i (voltage recovery), recomputed by set_sample_rate
    pub s_ni: [[f64; M]; N],
    /// S_be matrix: A_be^{-1} (backward Euler), recomputed by set_sample_rate
    pub s_be: [[f64; N]; N],
    /// K_be matrix: N_v * S_be * N_i (BE kernel), recomputed by set_sample_rate
    pub k_be: [[f64; M]; M],
    /// S_NI_be matrix: S_be * N_i (BE voltage recovery), recomputed by set_sample_rate
    pub s_ni_be: [[f64; M]; N],

    // --- Runtime-adjustable device parameters ---
    /// Device 0 IS (Bjt) — runtime adjustable
    pub device_0_is: f64,
    /// Device 0 VT (Bjt) — runtime adjustable
    pub device_0_vt: f64,
    /// Device 0 BETA_F (Bjt) — runtime adjustable
    pub device_0_bf: f64,
    /// Device 0 BETA_R (Bjt) — runtime adjustable
    pub device_0_br: f64,
    /// Device 1 IS (Bjt) — runtime adjustable
    pub device_1_is: f64,
    /// Device 1 VT (Bjt) — runtime adjustable
    pub device_1_vt: f64,
    /// Device 1 BETA_F (Bjt) — runtime adjustable
    pub device_1_bf: f64,
    /// Device 1 BETA_R (Bjt) — runtime adjustable
    pub device_1_br: f64,
}

impl Default for CircuitState {
    fn default() -> Self {
        Self {
            v_prev: DC_OP,
            i_nl_prev: DC_NL_I,
            i_nl_prev_prev: DC_NL_I,
            dc_operating_point: DC_OP,
            input_prev: 0.0,
            last_nr_iterations: 0,
            diag_peak_output: 0.0,
            diag_clamp_count: 0,
            diag_nr_max_iter_count: 0,
            diag_be_fallback_count: 0,
            diag_nan_reset_count: 0,
            a: A_DEFAULT,
            a_neg: A_NEG_DEFAULT,
            a_be: A_BE_DEFAULT,
            a_neg_be: A_NEG_BE_DEFAULT,
            s: S_DEFAULT,
            k: K_DEFAULT,
            s_ni: S_NI_DEFAULT,
            s_be: S_BE_DEFAULT,
            k_be: K_BE_DEFAULT,
            s_ni_be: S_NI_BE_DEFAULT,
            device_0_is: DEVICE_0_IS,
            device_0_vt: DEVICE_0_VT,
            device_0_bf: DEVICE_0_BETA_F,
            device_0_br: DEVICE_0_BETA_R,
            device_1_is: DEVICE_1_IS,
            device_1_vt: DEVICE_1_VT,
            device_1_bf: DEVICE_1_BETA_F,
            device_1_br: DEVICE_1_BETA_R,
        }
    }
}

impl CircuitState {
    /// Reset to DC operating point
    pub fn reset(&mut self) {
        self.v_prev = self.dc_operating_point;
        self.i_nl_prev = DC_NL_I;
        self.i_nl_prev_prev = DC_NL_I;
        self.input_prev = 0.0;
        self.last_nr_iterations = 0;
        self.diag_peak_output = 0.0;
        self.diag_clamp_count = 0;
        self.diag_nr_max_iter_count = 0;
        self.diag_be_fallback_count = 0;
        self.diag_nan_reset_count = 0;
        self.s = S_DEFAULT;
        self.k = K_DEFAULT;
        self.s_ni = S_NI_DEFAULT;
        self.s_be = S_BE_DEFAULT;
        self.k_be = K_BE_DEFAULT;
        self.s_ni_be = S_NI_BE_DEFAULT;
        self.device_0_is = DEVICE_0_IS;
        self.device_0_vt = DEVICE_0_VT;
        self.device_0_bf = DEVICE_0_BETA_F;
        self.device_0_br = DEVICE_0_BETA_R;
        self.device_1_is = DEVICE_1_IS;
        self.device_1_vt = DEVICE_1_VT;
        self.device_1_bf = DEVICE_1_BETA_F;
        self.device_1_br = DEVICE_1_BETA_R;
    }

    /// Set DC operating point (call after DC analysis)
    pub fn set_dc_operating_point(&mut self, v_dc: [f64; N]) {
        self.dc_operating_point = v_dc;
        self.v_prev = v_dc;
    }

    /// Recompute all sample-rate-dependent matrices for a new sample rate.
    ///
    /// Call this once during plugin initialization (NOT on the audio thread).
    /// Rebuilds A, A_neg, A_be, A_neg_be from stored G and C matrices.
    pub fn set_sample_rate(&mut self, sample_rate: f64) {
        if !(sample_rate > 0.0 && sample_rate.is_finite()) {
            return;
        }

        // If same as codegen sample rate, reset to defaults
        if (sample_rate - SAMPLE_RATE).abs() < 0.5 {
            self.a = A_DEFAULT;
            self.a_neg = A_NEG_DEFAULT;
            self.a_be = A_BE_DEFAULT;
            self.a_neg_be = A_NEG_BE_DEFAULT;
            self.s = S_DEFAULT;
            self.s_be = S_BE_DEFAULT;
            self.k = K_DEFAULT;
            self.s_ni = S_NI_DEFAULT;
            self.k_be = K_BE_DEFAULT;
            self.s_ni_be = S_NI_BE_DEFAULT;
            return;
        }

        let internal_rate = sample_rate * 1.0;
        let alpha = 2.0 * internal_rate;
        let alpha_be = internal_rate;

        self.rebuild_matrices(internal_rate);
    }

    /// Recompute A, A_neg, A_be, A_neg_be, S, K, S_NI (and BE variants) from G and C.
    ///
    /// Called by set_sample_rate, set_pot, and set_switch.
    /// Includes O(N^3) matrix inversion for Schur complement NR.
    pub fn rebuild_matrices(&mut self, internal_rate: f64) {
        let alpha = 2.0 * internal_rate;
        let alpha_be = internal_rate;

        for i in 0..N {
            for j in 0..N {
                self.a[i][j] = G[i][j] + alpha * C[i][j];
                self.a_neg[i][j] = alpha * C[i][j] - G[i][j];
                self.a_be[i][j] = G[i][j] + alpha_be * C[i][j];
                self.a_neg_be[i][j] = alpha_be * C[i][j];
            }
        }
        for i in 6..7 {
            for j in 0..N {
                self.a_neg[i][j] = 0.0;
                self.a_neg_be[i][j] = 0.0;
            }
        }

        // Recompute S = A^{-1} (trapezoidal)
        if let Some(inv) = invert_n(&self.a) {
            self.s = inv;
            // K = N_v * S * N_i
            for i in 0..M {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        let mut s_ni_aj = 0.0;
                        for b in 0..N {
                            s_ni_aj += self.s[a][b] * N_I[b][j];
                        }
                        sum += N_V[i][a] * s_ni_aj;
                    }
                    self.k[i][j] = sum;
                }
            }
            // S_NI = S * N_i
            for i in 0..N {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        sum += self.s[i][a] * N_I[a][j];
                    }
                    self.s_ni[i][j] = sum;
                }
            }
        }
        // Recompute S_be = A_be^{-1} (backward Euler)
        if let Some(inv) = invert_n(&self.a_be) {
            self.s_be = inv;
            for i in 0..M {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        let mut s_ni_aj = 0.0;
                        for b in 0..N {
                            s_ni_aj += self.s_be[a][b] * N_I[b][j];
                        }
                        sum += N_V[i][a] * s_ni_aj;
                    }
                    self.k_be[i][j] = sum;
                }
            }
            for i in 0..N {
                for j in 0..M {
                    let mut sum = 0.0;
                    for a in 0..N {
                        sum += self.s_be[i][a] * N_I[a][j];
                    }
                    self.s_ni_be[i][j] = sum;
                }
            }
        }
    }
}

// =============================================================================
// MATRIX INVERSION (for rebuild_matrices)
// =============================================================================

/// Invert an N×N matrix using Gauss-Jordan elimination with partial pivoting.
/// Returns None if the matrix is singular.
#[inline(never)]
fn invert_n(a: &[[f64; N]; N]) -> Option<[[f64; N]; N]> {
    let mut aug = [[0.0f64; 2 * N]; N];
    for i in 0..N {
        for j in 0..N {
            aug[i][j] = a[i][j];
        }
        aug[i][N + i] = 1.0;
    }

    for col in 0..N {
        let mut max_row = col;
        let mut max_val = aug[col][col].abs();
        for row in (col + 1)..N {
            let v = aug[row][col].abs();
            if v > max_val {
                max_val = v;
                max_row = row;
            }
        }
        if max_val < 1e-30 {
            return None;
        }
        if max_row != col {
            aug.swap(col, max_row);
        }
        let pivot = aug[col][col];
        for row in (col + 1)..N {
            let factor = aug[row][col] / pivot;
            for j in col..(2 * N) {
                aug[row][j] -= factor * aug[col][j];
            }
        }
    }

    for col in (0..N).rev() {
        let pivot = aug[col][col];
        if pivot.abs() < 1e-30 {
            return None;
        }
        for j in 0..(2 * N) {
            aug[col][j] /= pivot;
        }
        for row in 0..col {
            let factor = aug[row][col];
            for j in 0..(2 * N) {
                aug[row][j] -= factor * aug[col][j];
            }
        }
    }

    let mut result = [[0.0f64; N]; N];
    for i in 0..N {
        for j in 0..N {
            result[i][j] = aug[i][N + j];
        }
    }
    Some(result)
}

// =============================================================================
// LU SOLVE (Equilibrated Gaussian elimination with iterative refinement)
// =============================================================================

/// Solve A*x = b using equilibrated LU with partial pivoting + iterative refinement.
///
/// Diagonal equilibration scales rows/cols by 1/sqrt(|A[i][i]|) to reduce
/// condition number. One round of iterative refinement corrects residual error.
/// Matches the runtime solver's `solve_equilibrated()` for numerical parity.
/// Modifies `a` in place (LU factors). On success, `b` contains the solution.
#[inline(always)]
fn lu_solve(a: &mut [[f64; N]; N], b: &mut [f64; N]) -> bool {
    // Save original A and b for iterative refinement
    let a_orig = *a;
    let b_orig = *b;

    // Step 1: Diagonal equilibration — d[i] = 1/sqrt(|A[i][i]|)
    let mut d = [1.0f64; N];
    for i in 0..N {
        let diag = a[i][i].abs();
        if diag > 1e-30 {
            d[i] = 1.0 / diag.sqrt();
        }
    }
    for i in 0..N {
        for j in 0..N {
            a[i][j] *= d[i] * d[j];
        }
        b[i] *= d[i];
    }

    // Step 2: LU factorize with partial pivoting
    let mut perm = [0usize; N];
    for i in 0..N {
        perm[i] = i;
    }

    for col in 0..N {
        let mut max_row = col;
        let mut max_val = a[col][col].abs();
        for row in (col + 1)..N {
            if a[row][col].abs() > max_val {
                max_val = a[row][col].abs();
                max_row = row;
            }
        }
        if max_val < 1e-30 {
            return false;
        }
        if max_row != col {
            a.swap(col, max_row);
            perm.swap(col, max_row);
        }
        let pivot = a[col][col];
        for row in (col + 1)..N {
            let factor = a[row][col] / pivot;
            a[row][col] = factor; // Store L factor
            for j in (col + 1)..N {
                a[row][j] -= factor * a[col][j];
            }
        }
    }

    // Step 3: Solve LU * x_eq = D * P * b
    let mut x = [0.0f64; N];
    for i in 0..N {
        x[i] = d[perm[i]] * b_orig[perm[i]];
    }

    // Forward substitution (L)
    for i in 1..N {
        let mut sum = 0.0;
        for j in 0..i {
            sum += a[i][j] * x[j];
        }
        x[i] -= sum;
    }
    // Backward substitution (U)
    for i in (0..N).rev() {
        let mut sum = 0.0;
        for j in (i + 1)..N {
            sum += a[i][j] * x[j];
        }
        if a[i][i].abs() < 1e-30 {
            return false;
        }
        x[i] = (x[i] - sum) / a[i][i];
    }

    // Step 4: Iterative refinement
    let mut r = [0.0f64; N];
    for i in 0..N {
        let pi = perm[i];
        let mut ax_i = 0.0;
        for j in 0..N {
            ax_i += d[pi] * a_orig[pi][j] * d[j] * x[j];
        }
        r[i] = d[pi] * b_orig[pi] - ax_i;
    }
    // Solve LU * dx = r
    for i in 1..N {
        let mut sum = 0.0;
        for j in 0..i {
            sum += a[i][j] * r[j];
        }
        r[i] -= sum;
    }
    for i in (0..N).rev() {
        let mut sum = 0.0;
        for j in (i + 1)..N {
            sum += a[i][j] * r[j];
        }
        r[i] = (r[i] - sum) / a[i][i];
    }

    // Step 5: Apply correction and undo equilibration
    for i in 0..N {
        b[i] = d[i] * (x[i] + r[i]);
    }

    true
}

// =============================================================================
// PROCESS SAMPLE (Full-nodal NR with LU solve)
// =============================================================================

/// Process a single audio sample through the circuit.
///
/// Uses full-nodal Newton-Raphson with LU factorization per iteration.
/// Includes backward Euler fallback for unconditional stability.
#[inline]
pub fn process_sample(input: f64, state: &mut CircuitState) -> [f64; NUM_OUTPUTS] {
    let input = if input.is_finite() {
        input.clamp(-100.0, 100.0)
    } else {
        0.0
    };

    // Step 1: Build RHS (sparse A_neg * v_prev + sparse N_i * i_nl_prev)
    let mut rhs = RHS_CONST;
    rhs[0] += state.a_neg[0][0] * state.v_prev[0];
    rhs[0] += state.a_neg[0][1] * state.v_prev[1];
    rhs[0] += state.a_neg[0][3] * state.v_prev[3];
    rhs[0] += state.a_neg[0][5] * state.v_prev[5];
    rhs[1] += state.a_neg[1][0] * state.v_prev[0];
    rhs[1] += state.a_neg[1][1] * state.v_prev[1];
    rhs[1] += state.a_neg[1][2] * state.v_prev[2];
    rhs[2] += state.a_neg[2][1] * state.v_prev[1];
    rhs[2] += state.a_neg[2][2] * state.v_prev[2];
    rhs[2] += state.a_neg[2][3] * state.v_prev[3];
    rhs[3] += state.a_neg[3][0] * state.v_prev[0];
    rhs[3] += state.a_neg[3][2] * state.v_prev[2];
    rhs[3] += state.a_neg[3][3] * state.v_prev[3];
    rhs[4] += state.a_neg[4][4] * state.v_prev[4];
    rhs[5] += state.a_neg[5][0] * state.v_prev[0];
    rhs[5] += state.a_neg[5][5] * state.v_prev[5];
    rhs[5] += state.a_neg[5][6] * state.v_prev[6];
    rhs[0] += N_I[0][0] * state.i_nl_prev[0];
    rhs[0] += N_I[0][2] * state.i_nl_prev[2];
    rhs[2] += N_I[2][1] * state.i_nl_prev[1];
    rhs[4] += N_I[4][0] * state.i_nl_prev[0];
    rhs[4] += N_I[4][1] * state.i_nl_prev[1];
    rhs[4] += N_I[4][3] * state.i_nl_prev[3];

    let input_conductance = 1.0 / INPUT_RESISTANCE;
    // Input source (trapezoidal: (V_in + V_in_prev) * G_in)
    rhs[INPUT_NODE] += (input + state.input_prev) * input_conductance;
    state.input_prev = input;

    // Step 2: Newton-Raphson in full augmented voltage space
    let mut v = state.v_prev;
    let mut converged = false;
    let mut i_nl = [0.0f64; M];

    for iter in 0..MAX_ITER {
        // 2a. Extract nonlinear voltages: v_nl = N_v * v (sparse)
        let mut v_nl = [0.0f64; M];
        v_nl[0] = N_V[0][2] * v[2] + N_V[0][4] * v[4];
        v_nl[1] = N_V[1][0] * v[0] + N_V[1][2] * v[2];
        v_nl[2] = N_V[2][4] * v[4];
        v_nl[3] = N_V[3][0] * v[0] + N_V[3][4] * v[4];

        // 2b. Evaluate device currents and Jacobian (block-diagonal)
        let mut j_dev = [0.0f64; M * M];
        {
            // BJT 0
            let vbe = v_nl[0];
            let vbc = v_nl[1];
            let (ic, ib, jac) = bjt_evaluate(
                vbe,
                vbc,
                state.device_0_is,
                state.device_0_vt,
                DEVICE_0_NF,
                DEVICE_0_NR,
                state.device_0_bf,
                state.device_0_br,
                DEVICE_0_SIGN,
                DEVICE_0_USE_GP,
                DEVICE_0_VAF,
                DEVICE_0_VAR,
                DEVICE_0_IKF,
                DEVICE_0_IKR,
                DEVICE_0_ISE,
                DEVICE_0_NE,
                DEVICE_0_ISC,
                DEVICE_0_NC,
            );
            i_nl[0] = ic;
            i_nl[1] = ib;
            j_dev[0 * M + 0] = jac[0];
            j_dev[0 * M + 1] = jac[1];
            j_dev[1 * M + 0] = jac[2];
            j_dev[1 * M + 1] = jac[3];
        }
        {
            // BJT 1
            let vbe = v_nl[2];
            let vbc = v_nl[3];
            let (ic, ib, jac) = bjt_evaluate(
                vbe,
                vbc,
                state.device_1_is,
                state.device_1_vt,
                DEVICE_1_NF,
                DEVICE_1_NR,
                state.device_1_bf,
                state.device_1_br,
                DEVICE_1_SIGN,
                DEVICE_1_USE_GP,
                DEVICE_1_VAF,
                DEVICE_1_VAR,
                DEVICE_1_IKF,
                DEVICE_1_IKR,
                DEVICE_1_ISE,
                DEVICE_1_NE,
                DEVICE_1_ISC,
                DEVICE_1_NC,
            );
            i_nl[2] = ic;
            i_nl[3] = ib;
            j_dev[2 * M + 2] = jac[0];
            j_dev[2 * M + 3] = jac[1];
            j_dev[3 * M + 2] = jac[2];
            j_dev[3 * M + 3] = jac[3];
        }

        // 2c. Build Jacobian: G_aug = A - N_i * J_dev * N_v (sparse)
        let mut g_aug = state.a;
        g_aug[0][2] -= N_I[0][0] * j_dev[0 * M + 0] * N_V[0][2];
        g_aug[0][4] -= N_I[0][0] * j_dev[0 * M + 0] * N_V[0][4];
        g_aug[4][2] -= N_I[4][0] * j_dev[0 * M + 0] * N_V[0][2];
        g_aug[4][4] -= N_I[4][0] * j_dev[0 * M + 0] * N_V[0][4];
        g_aug[0][0] -= N_I[0][0] * j_dev[0 * M + 1] * N_V[1][0];
        g_aug[0][2] -= N_I[0][0] * j_dev[0 * M + 1] * N_V[1][2];
        g_aug[4][0] -= N_I[4][0] * j_dev[0 * M + 1] * N_V[1][0];
        g_aug[4][2] -= N_I[4][0] * j_dev[0 * M + 1] * N_V[1][2];
        g_aug[2][2] -= N_I[2][1] * j_dev[1 * M + 0] * N_V[0][2];
        g_aug[2][4] -= N_I[2][1] * j_dev[1 * M + 0] * N_V[0][4];
        g_aug[4][2] -= N_I[4][1] * j_dev[1 * M + 0] * N_V[0][2];
        g_aug[4][4] -= N_I[4][1] * j_dev[1 * M + 0] * N_V[0][4];
        g_aug[2][0] -= N_I[2][1] * j_dev[1 * M + 1] * N_V[1][0];
        g_aug[2][2] -= N_I[2][1] * j_dev[1 * M + 1] * N_V[1][2];
        g_aug[4][0] -= N_I[4][1] * j_dev[1 * M + 1] * N_V[1][0];
        g_aug[4][2] -= N_I[4][1] * j_dev[1 * M + 1] * N_V[1][2];
        g_aug[0][4] -= N_I[0][2] * j_dev[2 * M + 2] * N_V[2][4];
        g_aug[0][0] -= N_I[0][2] * j_dev[2 * M + 3] * N_V[3][0];
        g_aug[0][4] -= N_I[0][2] * j_dev[2 * M + 3] * N_V[3][4];
        g_aug[4][4] -= N_I[4][3] * j_dev[3 * M + 2] * N_V[2][4];
        g_aug[4][0] -= N_I[4][3] * j_dev[3 * M + 3] * N_V[3][0];
        g_aug[4][4] -= N_I[4][3] * j_dev[3 * M + 3] * N_V[3][4];

        // 2d. Build companion RHS: rhs + N_i * (i_nl - J_dev * v_nl) (sparse)
        let mut rhs_work = rhs;
        {
            let i_comp = i_nl[0] - (j_dev[0 * M + 0] * v_nl[0] + j_dev[0 * M + 1] * v_nl[1]);
            rhs_work[0] += N_I[0][0] * i_comp;
            rhs_work[4] += N_I[4][0] * i_comp;
        }
        {
            let i_comp = i_nl[1] - (j_dev[1 * M + 0] * v_nl[0] + j_dev[1 * M + 1] * v_nl[1]);
            rhs_work[2] += N_I[2][1] * i_comp;
            rhs_work[4] += N_I[4][1] * i_comp;
        }
        {
            let i_comp = i_nl[2] - (j_dev[2 * M + 2] * v_nl[2] + j_dev[2 * M + 3] * v_nl[3]);
            rhs_work[0] += N_I[0][2] * i_comp;
        }
        {
            let i_comp = i_nl[3] - (j_dev[3 * M + 2] * v_nl[2] + j_dev[3 * M + 3] * v_nl[3]);
            rhs_work[4] += N_I[4][3] * i_comp;
        }

        // 2e. LU solve: v_new = G_aug^{-1} * rhs_work
        let mut v_new = rhs_work;
        if !lu_solve(&mut g_aug, &mut v_new) {
            state.diag_nr_max_iter_count += 1;
            break;
        }

        // 2f. SPICE voltage limiting + node damping
        let mut alpha = 1.0_f64;

        // Layer 1: SPICE device voltage limiting
        {
            // Device 0 dim 0
            let mut v_nl_proposed = 0.0;
            for j in 0..N {
                v_nl_proposed += N_V[0][j] * v_new[j];
            }
            let v_nl_current = v_nl[0];
            let dv = v_nl_proposed - v_nl_current;
            if dv.abs() > 1e-15 {
                let v_lim = pnjlim(
                    v_nl_proposed,
                    v_nl_current,
                    state.device_0_vt,
                    DEVICE_0_VCRIT,
                );
                let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                if ratio < alpha {
                    alpha = ratio;
                }
            }
        }
        {
            // Device 0 dim 1
            let mut v_nl_proposed = 0.0;
            for j in 0..N {
                v_nl_proposed += N_V[1][j] * v_new[j];
            }
            let v_nl_current = v_nl[1];
            let dv = v_nl_proposed - v_nl_current;
            if dv.abs() > 1e-15 {
                let v_lim = pnjlim(
                    v_nl_proposed,
                    v_nl_current,
                    state.device_0_vt,
                    DEVICE_0_VCRIT,
                );
                let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                if ratio < alpha {
                    alpha = ratio;
                }
            }
        }
        {
            // Device 1 dim 0
            let mut v_nl_proposed = 0.0;
            for j in 0..N {
                v_nl_proposed += N_V[2][j] * v_new[j];
            }
            let v_nl_current = v_nl[2];
            let dv = v_nl_proposed - v_nl_current;
            if dv.abs() > 1e-15 {
                let v_lim = pnjlim(
                    v_nl_proposed,
                    v_nl_current,
                    state.device_1_vt,
                    DEVICE_1_VCRIT,
                );
                let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                if ratio < alpha {
                    alpha = ratio;
                }
            }
        }
        {
            // Device 1 dim 1
            let mut v_nl_proposed = 0.0;
            for j in 0..N {
                v_nl_proposed += N_V[3][j] * v_new[j];
            }
            let v_nl_current = v_nl[3];
            let dv = v_nl_proposed - v_nl_current;
            if dv.abs() > 1e-15 {
                let v_lim = pnjlim(
                    v_nl_proposed,
                    v_nl_current,
                    state.device_1_vt,
                    DEVICE_1_VCRIT,
                );
                let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                if ratio < alpha {
                    alpha = ratio;
                }
            }
        }

        // Layer 2: Global node voltage damping
        {
            let mut max_node_dv = 0.0_f64;
            for i in 0..6 {
                let dv = alpha * (v_new[i] - v[i]);
                max_node_dv = max_node_dv.max(dv.abs());
            }
            let mut max_v = 0.0_f64;
            for i in 0..6 {
                max_v = max_v.max(v[i].abs());
            }
            let damp_thresh = 10.0_f64.max(max_v * 0.05);
            if max_node_dv > damp_thresh {
                alpha *= (damp_thresh / max_node_dv).max(0.01);
            }
        }

        // Compute damped step, check convergence, then apply
        let mut max_step_exceeded = false;
        for i in 0..N {
            let step = alpha * (v_new[i] - v[i]);
            let threshold = 1e-6 * v[i].abs().max((v[i] + step).abs()) + TOL;
            if step.abs() >= threshold {
                max_step_exceeded = true;
            }
            v[i] += step;
        }
        let converged_check = !max_step_exceeded;

        if converged_check {
            converged = true;
            state.last_nr_iterations = iter as u32;
            // Final device evaluation at converged point
            let mut v_nl_final = [0.0f64; M];
            for i in 0..M {
                let mut sum = 0.0;
                for j in 0..N {
                    sum += N_V[i][j] * v[j];
                }
                v_nl_final[i] = sum;
            }
            {
                let vbe = v_nl_final[0];
                let vbc = v_nl_final[1];
                let (ic, ib, _) = bjt_evaluate(
                    vbe,
                    vbc,
                    state.device_0_is,
                    state.device_0_vt,
                    DEVICE_0_NF,
                    DEVICE_0_NR,
                    state.device_0_bf,
                    state.device_0_br,
                    DEVICE_0_SIGN,
                    DEVICE_0_USE_GP,
                    DEVICE_0_VAF,
                    DEVICE_0_VAR,
                    DEVICE_0_IKF,
                    DEVICE_0_IKR,
                    DEVICE_0_ISE,
                    DEVICE_0_NE,
                    DEVICE_0_ISC,
                    DEVICE_0_NC,
                );
                i_nl[0] = ic;
                i_nl[1] = ib;
            }
            {
                let vbe = v_nl_final[2];
                let vbc = v_nl_final[3];
                let (ic, ib, _) = bjt_evaluate(
                    vbe,
                    vbc,
                    state.device_1_is,
                    state.device_1_vt,
                    DEVICE_1_NF,
                    DEVICE_1_NR,
                    state.device_1_bf,
                    state.device_1_br,
                    DEVICE_1_SIGN,
                    DEVICE_1_USE_GP,
                    DEVICE_1_VAF,
                    DEVICE_1_VAR,
                    DEVICE_1_IKF,
                    DEVICE_1_IKR,
                    DEVICE_1_ISE,
                    DEVICE_1_NE,
                    DEVICE_1_ISC,
                    DEVICE_1_NC,
                );
                i_nl[2] = ic;
                i_nl[3] = ib;
            }
            break;
        }
    }

    // Backward Euler fallback: if trapezoidal NR didn't converge, retry with BE
    if !converged {
        state.diag_nr_max_iter_count += 1;

        // Rebuild RHS with backward Euler matrices
        v = state.v_prev;
        let mut rhs_be = [0.0f64; N];
        for i in 0..N {
            let mut sum = RHS_CONST_BE[i];
            for j in 0..N {
                sum += state.a_neg_be[i][j] * state.v_prev[j];
            }
            for j in 0..M {
                sum += N_I[i][j] * state.i_nl_prev[j];
            }
            rhs_be[i] = sum;
        }
        // BE input: just input[n+1] * G_in (no trapezoidal average)
        rhs_be[INPUT_NODE] += input * input_conductance;

        for _iter in 0..MAX_ITER {
            let mut v_nl = [0.0f64; M];
            for i in 0..M {
                let mut sum = 0.0;
                for j in 0..N {
                    sum += N_V[i][j] * v[j];
                }
                v_nl[i] = sum;
            }

            // Evaluate devices
            let mut j_dev = [0.0f64; M * M];
            {
                // BJT 0
                let vbe = v_nl[0];
                let vbc = v_nl[1];
                let (ic, ib, jac) = bjt_evaluate(
                    vbe,
                    vbc,
                    state.device_0_is,
                    state.device_0_vt,
                    DEVICE_0_NF,
                    DEVICE_0_NR,
                    state.device_0_bf,
                    state.device_0_br,
                    DEVICE_0_SIGN,
                    DEVICE_0_USE_GP,
                    DEVICE_0_VAF,
                    DEVICE_0_VAR,
                    DEVICE_0_IKF,
                    DEVICE_0_IKR,
                    DEVICE_0_ISE,
                    DEVICE_0_NE,
                    DEVICE_0_ISC,
                    DEVICE_0_NC,
                );
                i_nl[0] = ic;
                i_nl[1] = ib;
                j_dev[0 * M + 0] = jac[0];
                j_dev[0 * M + 1] = jac[1];
                j_dev[1 * M + 0] = jac[2];
                j_dev[1 * M + 1] = jac[3];
            }
            {
                // BJT 1
                let vbe = v_nl[2];
                let vbc = v_nl[3];
                let (ic, ib, jac) = bjt_evaluate(
                    vbe,
                    vbc,
                    state.device_1_is,
                    state.device_1_vt,
                    DEVICE_1_NF,
                    DEVICE_1_NR,
                    state.device_1_bf,
                    state.device_1_br,
                    DEVICE_1_SIGN,
                    DEVICE_1_USE_GP,
                    DEVICE_1_VAF,
                    DEVICE_1_VAR,
                    DEVICE_1_IKF,
                    DEVICE_1_IKR,
                    DEVICE_1_ISE,
                    DEVICE_1_NE,
                    DEVICE_1_ISC,
                    DEVICE_1_NC,
                );
                i_nl[2] = ic;
                i_nl[3] = ib;
                j_dev[2 * M + 2] = jac[0];
                j_dev[2 * M + 3] = jac[1];
                j_dev[3 * M + 2] = jac[2];
                j_dev[3 * M + 3] = jac[3];
            }

            let mut g_aug = state.a_be;
            g_aug[0][2] -= N_I[0][0] * j_dev[0 * M + 0] * N_V[0][2];
            g_aug[0][4] -= N_I[0][0] * j_dev[0 * M + 0] * N_V[0][4];
            g_aug[4][2] -= N_I[4][0] * j_dev[0 * M + 0] * N_V[0][2];
            g_aug[4][4] -= N_I[4][0] * j_dev[0 * M + 0] * N_V[0][4];
            g_aug[0][0] -= N_I[0][0] * j_dev[0 * M + 1] * N_V[1][0];
            g_aug[0][2] -= N_I[0][0] * j_dev[0 * M + 1] * N_V[1][2];
            g_aug[4][0] -= N_I[4][0] * j_dev[0 * M + 1] * N_V[1][0];
            g_aug[4][2] -= N_I[4][0] * j_dev[0 * M + 1] * N_V[1][2];
            g_aug[2][2] -= N_I[2][1] * j_dev[1 * M + 0] * N_V[0][2];
            g_aug[2][4] -= N_I[2][1] * j_dev[1 * M + 0] * N_V[0][4];
            g_aug[4][2] -= N_I[4][1] * j_dev[1 * M + 0] * N_V[0][2];
            g_aug[4][4] -= N_I[4][1] * j_dev[1 * M + 0] * N_V[0][4];
            g_aug[2][0] -= N_I[2][1] * j_dev[1 * M + 1] * N_V[1][0];
            g_aug[2][2] -= N_I[2][1] * j_dev[1 * M + 1] * N_V[1][2];
            g_aug[4][0] -= N_I[4][1] * j_dev[1 * M + 1] * N_V[1][0];
            g_aug[4][2] -= N_I[4][1] * j_dev[1 * M + 1] * N_V[1][2];
            g_aug[0][4] -= N_I[0][2] * j_dev[2 * M + 2] * N_V[2][4];
            g_aug[0][0] -= N_I[0][2] * j_dev[2 * M + 3] * N_V[3][0];
            g_aug[0][4] -= N_I[0][2] * j_dev[2 * M + 3] * N_V[3][4];
            g_aug[4][4] -= N_I[4][3] * j_dev[3 * M + 2] * N_V[2][4];
            g_aug[4][0] -= N_I[4][3] * j_dev[3 * M + 3] * N_V[3][0];
            g_aug[4][4] -= N_I[4][3] * j_dev[3 * M + 3] * N_V[3][4];

            let mut rhs_work = rhs_be;
            {
                let i_comp = i_nl[0] - (j_dev[0 * M + 0] * v_nl[0] + j_dev[0 * M + 1] * v_nl[1]);
                rhs_work[0] += N_I[0][0] * i_comp;
                rhs_work[4] += N_I[4][0] * i_comp;
            }
            {
                let i_comp = i_nl[1] - (j_dev[1 * M + 0] * v_nl[0] + j_dev[1 * M + 1] * v_nl[1]);
                rhs_work[2] += N_I[2][1] * i_comp;
                rhs_work[4] += N_I[4][1] * i_comp;
            }
            {
                let i_comp = i_nl[2] - (j_dev[2 * M + 2] * v_nl[2] + j_dev[2 * M + 3] * v_nl[3]);
                rhs_work[0] += N_I[0][2] * i_comp;
            }
            {
                let i_comp = i_nl[3] - (j_dev[3 * M + 2] * v_nl[2] + j_dev[3 * M + 3] * v_nl[3]);
                rhs_work[4] += N_I[4][3] * i_comp;
            }

            let mut v_new = rhs_work;
            if !lu_solve(&mut g_aug, &mut v_new) {
                break;
            }

            let mut alpha = 1.0_f64;
            {
                // Device 0 dim 0
                let mut v_nl_proposed = 0.0;
                for j in 0..N {
                    v_nl_proposed += N_V[0][j] * v_new[j];
                }
                let v_nl_current = v_nl[0];
                let dv = v_nl_proposed - v_nl_current;
                if dv.abs() > 1e-15 {
                    let v_lim = pnjlim(
                        v_nl_proposed,
                        v_nl_current,
                        state.device_0_vt,
                        DEVICE_0_VCRIT,
                    );
                    let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                    if ratio < alpha {
                        alpha = ratio;
                    }
                }
            }
            {
                // Device 0 dim 1
                let mut v_nl_proposed = 0.0;
                for j in 0..N {
                    v_nl_proposed += N_V[1][j] * v_new[j];
                }
                let v_nl_current = v_nl[1];
                let dv = v_nl_proposed - v_nl_current;
                if dv.abs() > 1e-15 {
                    let v_lim = pnjlim(
                        v_nl_proposed,
                        v_nl_current,
                        state.device_0_vt,
                        DEVICE_0_VCRIT,
                    );
                    let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                    if ratio < alpha {
                        alpha = ratio;
                    }
                }
            }
            {
                // Device 1 dim 0
                let mut v_nl_proposed = 0.0;
                for j in 0..N {
                    v_nl_proposed += N_V[2][j] * v_new[j];
                }
                let v_nl_current = v_nl[2];
                let dv = v_nl_proposed - v_nl_current;
                if dv.abs() > 1e-15 {
                    let v_lim = pnjlim(
                        v_nl_proposed,
                        v_nl_current,
                        state.device_1_vt,
                        DEVICE_1_VCRIT,
                    );
                    let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                    if ratio < alpha {
                        alpha = ratio;
                    }
                }
            }
            {
                // Device 1 dim 1
                let mut v_nl_proposed = 0.0;
                for j in 0..N {
                    v_nl_proposed += N_V[3][j] * v_new[j];
                }
                let v_nl_current = v_nl[3];
                let dv = v_nl_proposed - v_nl_current;
                if dv.abs() > 1e-15 {
                    let v_lim = pnjlim(
                        v_nl_proposed,
                        v_nl_current,
                        state.device_1_vt,
                        DEVICE_1_VCRIT,
                    );
                    let ratio = ((v_lim - v_nl_current) / dv).clamp(0.01, 1.0);
                    if ratio < alpha {
                        alpha = ratio;
                    }
                }
            }
            {
                let mut max_node_dv = 0.0_f64;
                for i in 0..6 {
                    let dv = alpha * (v_new[i] - v[i]);
                    max_node_dv = max_node_dv.max(dv.abs());
                }
                if max_node_dv > 10.0 {
                    alpha *= (10.0 / max_node_dv).max(0.01);
                }
            }

            let mut be_step_exceeded = false;
            for i in 0..N {
                let step = alpha * (v_new[i] - v[i]);
                let threshold = 1e-6 * v[i].abs().max((v[i] + step).abs()) + TOL;
                if step.abs() >= threshold {
                    be_step_exceeded = true;
                }
                v[i] += step;
            }
            let be_converged = !be_step_exceeded;

            if be_converged {
                converged = true;
                state.diag_be_fallback_count += 1;
                let mut v_nl_final = [0.0f64; M];
                for i in 0..M {
                    let mut sum = 0.0;
                    for j in 0..N {
                        sum += N_V[i][j] * v[j];
                    }
                    v_nl_final[i] = sum;
                }
                {
                    let vbe = v_nl_final[0];
                    let vbc = v_nl_final[1];
                    let (ic, ib, _) = bjt_evaluate(
                        vbe,
                        vbc,
                        state.device_0_is,
                        state.device_0_vt,
                        DEVICE_0_NF,
                        DEVICE_0_NR,
                        state.device_0_bf,
                        state.device_0_br,
                        DEVICE_0_SIGN,
                        DEVICE_0_USE_GP,
                        DEVICE_0_VAF,
                        DEVICE_0_VAR,
                        DEVICE_0_IKF,
                        DEVICE_0_IKR,
                        DEVICE_0_ISE,
                        DEVICE_0_NE,
                        DEVICE_0_ISC,
                        DEVICE_0_NC,
                    );
                    i_nl[0] = ic;
                    i_nl[1] = ib;
                }
                {
                    let vbe = v_nl_final[2];
                    let vbc = v_nl_final[3];
                    let (ic, ib, _) = bjt_evaluate(
                        vbe,
                        vbc,
                        state.device_1_is,
                        state.device_1_vt,
                        DEVICE_1_NF,
                        DEVICE_1_NR,
                        state.device_1_bf,
                        state.device_1_br,
                        DEVICE_1_SIGN,
                        DEVICE_1_USE_GP,
                        DEVICE_1_VAF,
                        DEVICE_1_VAR,
                        DEVICE_1_IKF,
                        DEVICE_1_IKR,
                        DEVICE_1_ISE,
                        DEVICE_1_NE,
                        DEVICE_1_ISC,
                        DEVICE_1_NC,
                    );
                    i_nl[2] = ic;
                    i_nl[3] = ib;
                }
                break;
            }
        }

        // If still not converged, ensure i_nl is consistent with v
        if !converged {
            let mut v_nl_final = [0.0f64; M];
            for i in 0..M {
                let mut sum = 0.0;
                for j in 0..N {
                    sum += N_V[i][j] * v[j];
                }
                v_nl_final[i] = sum;
            }
            {
                let vbe = v_nl_final[0];
                let vbc = v_nl_final[1];
                let (ic, ib, _) = bjt_evaluate(
                    vbe,
                    vbc,
                    state.device_0_is,
                    state.device_0_vt,
                    DEVICE_0_NF,
                    DEVICE_0_NR,
                    state.device_0_bf,
                    state.device_0_br,
                    DEVICE_0_SIGN,
                    DEVICE_0_USE_GP,
                    DEVICE_0_VAF,
                    DEVICE_0_VAR,
                    DEVICE_0_IKF,
                    DEVICE_0_IKR,
                    DEVICE_0_ISE,
                    DEVICE_0_NE,
                    DEVICE_0_ISC,
                    DEVICE_0_NC,
                );
                i_nl[0] = ic;
                i_nl[1] = ib;
            }
            {
                let vbe = v_nl_final[2];
                let vbc = v_nl_final[3];
                let (ic, ib, _) = bjt_evaluate(
                    vbe,
                    vbc,
                    state.device_1_is,
                    state.device_1_vt,
                    DEVICE_1_NF,
                    DEVICE_1_NR,
                    state.device_1_bf,
                    state.device_1_br,
                    DEVICE_1_SIGN,
                    DEVICE_1_USE_GP,
                    DEVICE_1_VAF,
                    DEVICE_1_VAR,
                    DEVICE_1_IKF,
                    DEVICE_1_IKR,
                    DEVICE_1_ISE,
                    DEVICE_1_NE,
                    DEVICE_1_ISC,
                    DEVICE_1_NC,
                );
                i_nl[2] = ic;
                i_nl[3] = ib;
            }
        }
    }

    if !v.iter().all(|x| x.is_finite()) {
        state.v_prev = state.dc_operating_point;
        state.i_nl_prev = [0.0; M];
        state.i_nl_prev_prev = [0.0; M];
        state.input_prev = 0.0;
        state.diag_nan_reset_count += 1;
        return [0.0; NUM_OUTPUTS];
    }

    // Step 3: Update state
    state.v_prev = v;
    state.i_nl_prev_prev = state.i_nl_prev;
    state.i_nl_prev = i_nl;

    if state.last_nr_iterations >= MAX_ITER as u32 {
        state.diag_nr_max_iter_count += 1;
    }

    // Step 4: Extract outputs, DC blocking, and scaling
    let mut output = [0.0f64; NUM_OUTPUTS];
    for out_idx in 0..NUM_OUTPUTS {
        let raw_out = v[OUTPUT_NODES[out_idx]];
        let raw_out = if raw_out.is_finite() { raw_out } else { 0.0 };
        let scaled = raw_out * OUTPUT_SCALES[out_idx];
        let abs_out = scaled.abs();
        if abs_out > state.diag_peak_output {
            state.diag_peak_output = abs_out;
        }
        output[out_idx] = if scaled.is_finite() { scaled } else { 0.0 };
    }
    output
}
